package xerr

// 成功返回
const OK uint32 = 200

/**(前3位代表业务，后3位代表具体功能)**/

// 全局错误码
const (
	SERVER_COMMON_ERROR   uint32 = 100001 + iota
	REQUEST_PARAM_ERROR
	TOKEN_EXPIRE_ERROR
	TOKEN_GENERATE_ERROR
	DB_ERROR
	DB_UPDATE_AFFECTED_ZERO_ERROR
	DB_ERROR_NOT_FOUND
	DB_TRANSACTION_ERROR
	REDIS_ERROR
)

// 用户模块
const (
	USER_NOT_FOUND         uint32 = 200001 + iota
	WRONG_PASSWORD
	USER_ALREADY_EXISTS
	EMPTY_USER_INFO
	EMAIL_ALREADY_USED
	PHONE_ALREADY_USED
	OLD_PASSWORD_ERROR
	USER_NOT_LOGIN
)

// 活动/场次/票种模块
const (
	EVENT_NOT_FOUND             uint32 = 300001 + iota
	EVENT_NAME_EMPTY
	EVENT_LOCATION_EMPTY
	EVENT_START_TIME_EMPTY
	EVENT_END_TIME_EMPTY
	EVENT_TIME_INVALID
	EVENT_ALREADY_EXISTS
	EVENT_STATUS_INVALID
	SHOW_NOT_FOUND
	TICKET_TYPE_NOT_FOUND
	TICKET_TYPE_EVENT_NOT_FOUND
	TICKET_TYPE_STATUS_INVALID
	NO_DATA_TO_UPDATE
	SHOW_NAME_EMPTY
	SHOW_TIME_INVALID
	SHOW_EVENT_NOT_MATCH
)

// 票务模块
const (
	TICKET_NOT_FOUND  uint32 = 400001 + iota
	TICKET_VERIFY_FAIL
	TICKET_REFUND_FAIL
	TICKET_TRANSFER_FAIL
	TICKET_CREATE_FAIL
)

// 库存模块
const (
	STOCK_NOT_ENOUGH     uint32 = 500001 + iota
	STOCK_INIT_FAIL
	STOCK_UPDATE_FAIL
	STOCK_DEDUCT_FAIL
	STOCK_RELEASE_FAIL
)

// 订单模块
const (
	ORDER_NOT_FOUND      uint32 = 600001 + iota
	ORDER_CREATE_FAIL
	ORDER_CANCEL_FAIL
	ORDER_UPDATE_FAIL
	ORDER_STATUS_INVALID
	ORDER_DUPLICATE
	ORDER_TIMEOUT
)

// 支付模块
const (
	PAY_FAIL        uint32 = 700001 + iota
	PAY_ORDER_NOT_FOUND
	PAY_STATUS_INVALID
	PAY_DUPLICATE
)
