// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: pay.proto

package paymentclient

import (
	"context"

	"Ticket/app/payment/pay-rpc/payment"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PayReq  = payment.PayReq
	PayResp = payment.PayResp

	Payment interface {
		// 模拟支付
		Pay(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error)
	}

	defaultPayment struct {
		cli zrpc.Client
	}
)

func NewPayment(cli zrpc.Client) Payment {
	return &defaultPayment{
		cli: cli,
	}
}

// 模拟支付
func (m *defaultPayment) Pay(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error) {
	client := payment.NewPaymentClient(m.cli.Conn())
	return client.Pay(ctx, in, opts...)
}
