// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: inventory.proto

package inventoryclient

import (
	"context"

	"Ticket/app/inventory/inventory-rpc/inventory"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResp       = inventory.CommonResp
	DeductStockReq   = inventory.DeductStockReq
	DeductStockResp  = inventory.DeductStockResp
	GetStockReq      = inventory.GetStockReq
	GetStockResp     = inventory.GetStockResp
	InitStockReq     = inventory.InitStockReq
	ReleaseStockReq  = inventory.ReleaseStockReq
	ReleaseStockResp = inventory.ReleaseStockResp
	UpdateStockReq   = inventory.UpdateStockReq

	Inventory interface {
		// 初始化库存
		InitStock(ctx context.Context, in *InitStockReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 查询库存
		GetStock(ctx context.Context, in *GetStockReq, opts ...grpc.CallOption) (*GetStockResp, error)
		// 扣库存
		DeductStock(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*DeductStockResp, error)
		// 回滚库存
		ReleaseStock(ctx context.Context, in *ReleaseStockReq, opts ...grpc.CallOption) (*ReleaseStockResp, error)
		// 修改库存
		UpdateStock(ctx context.Context, in *UpdateStockReq, opts ...grpc.CallOption) (*CommonResp, error)
	}

	defaultInventory struct {
		cli zrpc.Client
	}
)

func NewInventory(cli zrpc.Client) Inventory {
	return &defaultInventory{
		cli: cli,
	}
}

// 初始化库存
func (m *defaultInventory) InitStock(ctx context.Context, in *InitStockReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := inventory.NewInventoryClient(m.cli.Conn())
	return client.InitStock(ctx, in, opts...)
}

// 查询库存
func (m *defaultInventory) GetStock(ctx context.Context, in *GetStockReq, opts ...grpc.CallOption) (*GetStockResp, error) {
	client := inventory.NewInventoryClient(m.cli.Conn())
	return client.GetStock(ctx, in, opts...)
}

// 扣库存
func (m *defaultInventory) DeductStock(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*DeductStockResp, error) {
	client := inventory.NewInventoryClient(m.cli.Conn())
	return client.DeductStock(ctx, in, opts...)
}

// 回滚库存
func (m *defaultInventory) ReleaseStock(ctx context.Context, in *ReleaseStockReq, opts ...grpc.CallOption) (*ReleaseStockResp, error) {
	client := inventory.NewInventoryClient(m.cli.Conn())
	return client.ReleaseStock(ctx, in, opts...)
}

// 修改库存
func (m *defaultInventory) UpdateStock(ctx context.Context, in *UpdateStockReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := inventory.NewInventoryClient(m.cli.Conn())
	return client.UpdateStock(ctx, in, opts...)
}
