// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ticket.proto

package ticketclient

import (
	"context"

	"Ticket/app/ticket/ticket-rpc/ticket"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResp           = ticket.CommonResp
	CreateTicketReq      = ticket.CreateTicketReq
	GetTicketReq         = ticket.GetTicketReq
	ListEventTicketsReq  = ticket.ListEventTicketsReq
	ListEventTicketsResp = ticket.ListEventTicketsResp
	ListUserTicketsReq   = ticket.ListUserTicketsReq
	ListUserTicketsResp  = ticket.ListUserTicketsResp
	RefundTicketReq      = ticket.RefundTicketReq
	TicketInfo           = ticket.TicketInfo
	TransferTicketReq    = ticket.TransferTicketReq
	VerifyTicketReq      = ticket.VerifyTicketReq

	Ticket interface {
		// 出票（支付成功后调用）
		CreateTicket(ctx context.Context, in *CreateTicketReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 查询票详情
		GetTicket(ctx context.Context, in *GetTicketReq, opts ...grpc.CallOption) (*TicketInfo, error)
		// 我的票（分页）
		ListUserTickets(ctx context.Context, in *ListUserTicketsReq, opts ...grpc.CallOption) (*ListUserTicketsResp, error)
		// 验票（扫码）
		VerifyTicket(ctx context.Context, in *VerifyTicketReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 退票
		RefundTicket(ctx context.Context, in *RefundTicketReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 转赠
		TransferTicket(ctx context.Context, in *TransferTicketReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 管理员查看某活动所有票
		ListEventTickets(ctx context.Context, in *ListEventTicketsReq, opts ...grpc.CallOption) (*ListEventTicketsResp, error)
	}

	defaultTicket struct {
		cli zrpc.Client
	}
)

func NewTicket(cli zrpc.Client) Ticket {
	return &defaultTicket{
		cli: cli,
	}
}

// 出票（支付成功后调用）
func (m *defaultTicket) CreateTicket(ctx context.Context, in *CreateTicketReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := ticket.NewTicketClient(m.cli.Conn())
	return client.CreateTicket(ctx, in, opts...)
}

// 查询票详情
func (m *defaultTicket) GetTicket(ctx context.Context, in *GetTicketReq, opts ...grpc.CallOption) (*TicketInfo, error) {
	client := ticket.NewTicketClient(m.cli.Conn())
	return client.GetTicket(ctx, in, opts...)
}

// 我的票（分页）
func (m *defaultTicket) ListUserTickets(ctx context.Context, in *ListUserTicketsReq, opts ...grpc.CallOption) (*ListUserTicketsResp, error) {
	client := ticket.NewTicketClient(m.cli.Conn())
	return client.ListUserTickets(ctx, in, opts...)
}

// 验票（扫码）
func (m *defaultTicket) VerifyTicket(ctx context.Context, in *VerifyTicketReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := ticket.NewTicketClient(m.cli.Conn())
	return client.VerifyTicket(ctx, in, opts...)
}

// 退票
func (m *defaultTicket) RefundTicket(ctx context.Context, in *RefundTicketReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := ticket.NewTicketClient(m.cli.Conn())
	return client.RefundTicket(ctx, in, opts...)
}

// 转赠
func (m *defaultTicket) TransferTicket(ctx context.Context, in *TransferTicketReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := ticket.NewTicketClient(m.cli.Conn())
	return client.TransferTicket(ctx, in, opts...)
}

// 管理员查看某活动所有票
func (m *defaultTicket) ListEventTickets(ctx context.Context, in *ListEventTicketsReq, opts ...grpc.CallOption) (*ListEventTicketsResp, error) {
	client := ticket.NewTicketClient(m.cli.Conn())
	return client.ListEventTickets(ctx, in, opts...)
}
