// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: order.proto

package server

import (
	"context"

	"Ticket/app/order/order-rpc/internal/logic"
	"Ticket/app/order/order-rpc/internal/svc"
	"Ticket/app/order/order-rpc/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

// 创建订单
func (s *OrderServer) CreateOrder(ctx context.Context, in *order.CreateOrderReq) (*order.CreateOrderResp, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

// 修改订单状态
func (s *OrderServer) UpdateOrderStatus(ctx context.Context, in *order.UpdateStatusReq) (*order.UpdateStatusResp, error) {
	l := logic.NewUpdateOrderStatusLogic(ctx, s.svcCtx)
	return l.UpdateOrderStatus(in)
}

// 删除订单
func (s *OrderServer) DeleteOrder(ctx context.Context, in *order.DeleteOrderReq) (*order.DeleteOrderResp, error) {
	l := logic.NewDeleteOrderLogic(ctx, s.svcCtx)
	return l.DeleteOrder(in)
}

// 修改订单信息
func (s *OrderServer) UpdateOrder(ctx context.Context, in *order.UpdateOrderReq) (*order.UpdateOrderResp, error) {
	l := logic.NewUpdateOrderLogic(ctx, s.svcCtx)
	return l.UpdateOrder(in)
}

// 获取订单详情
func (s *OrderServer) GetOrder(ctx context.Context, in *order.GetOrderReq) (*order.GetOrderResp, error) {
	l := logic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}

// 获取用户订单列表
func (s *OrderServer) GetOrderList(ctx context.Context, in *order.GetOrderListReq) (*order.GetOrderListResp, error) {
	l := logic.NewGetOrderListLogic(ctx, s.svcCtx)
	return l.GetOrderList(in)
}

// 取消订单
func (s *OrderServer) CancelOrder(ctx context.Context, in *order.CancelOrderReq) (*order.CancelOrderResp, error) {
	l := logic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}
