//订单

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: order.proto

package order

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	EventId       uint64                 `protobuf:"varint,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	ShowId        uint32                 `protobuf:"varint,3,opt,name=showId,proto3" json:"showId,omitempty"`
	TicketTypeId  uint32                 `protobuf:"varint,4,opt,name=ticketTypeId,proto3" json:"ticketTypeId,omitempty"`
	OrderNo       string                 `protobuf:"bytes,5,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,7,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderInfo) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderInfo) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *OrderInfo) GetShowId() uint32 {
	if x != nil {
		return x.ShowId
	}
	return 0
}

func (x *OrderInfo) GetTicketTypeId() uint32 {
	if x != nil {
		return x.TicketTypeId
	}
	return 0
}

func (x *OrderInfo) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderInfo) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderInfo) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *OrderInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"varint,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	EventId       uint64                 `protobuf:"varint,3,opt,name=eventId,proto3" json:"eventId,omitempty"`
	ShowId        uint32                 `protobuf:"varint,4,opt,name=showId,proto3" json:"showId,omitempty"`
	TicketTypeId  uint32                 `protobuf:"varint,5,opt,name=ticketTypeId,proto3" json:"ticketTypeId,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,7,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderReq) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateOrderReq) GetShowId() uint32 {
	if x != nil {
		return x.ShowId
	}
	return 0
}

func (x *CreateOrderReq) GetTicketTypeId() uint32 {
	if x != nil {
		return x.TicketTypeId
	}
	return 0
}

func (x *CreateOrderReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateOrderReq) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type CreateOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderInfo             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResp) Reset() {
	*x = CreateOrderResp{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResp) ProtoMessage() {}

func (x *CreateOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResp.ProtoReflect.Descriptor instead.
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResp) GetOrder() *OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

type UpdateStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusReq) Reset() {
	*x = UpdateStatusReq{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusReq) ProtoMessage() {}

func (x *UpdateStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateStatusReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateStatusReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *UpdateStatusReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusResp) Reset() {
	*x = UpdateStatusResp{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResp) ProtoMessage() {}

func (x *UpdateStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResp.ProtoReflect.Descriptor instead.
func (*UpdateStatusResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStatusResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderReq) Reset() {
	*x = DeleteOrderReq{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderReq) ProtoMessage() {}

func (x *DeleteOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderReq.ProtoReflect.Descriptor instead.
func (*DeleteOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteOrderReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type DeleteOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderResp) Reset() {
	*x = DeleteOrderResp{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderResp) ProtoMessage() {}

func (x *DeleteOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderResp.ProtoReflect.Descriptor instead.
func (*DeleteOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteOrderResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderReq) Reset() {
	*x = UpdateOrderReq{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderReq) ProtoMessage() {}

func (x *UpdateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderReq.ProtoReflect.Descriptor instead.
func (*UpdateOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateOrderReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *UpdateOrderReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderInfo             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderResp) Reset() {
	*x = UpdateOrderResp{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderResp) ProtoMessage() {}

func (x *UpdateOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderResp.ProtoReflect.Descriptor instead.
func (*UpdateOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateOrderResp) GetOrder() *OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReq) Reset() {
	*x = GetOrderReq{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReq) ProtoMessage() {}

func (x *GetOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReq.ProtoReflect.Descriptor instead.
func (*GetOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type GetOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderInfo             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResp) Reset() {
	*x = GetOrderResp{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResp) ProtoMessage() {}

func (x *GetOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResp.ProtoReflect.Descriptor instead.
func (*GetOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *GetOrderResp) GetOrder() *OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderListReq) Reset() {
	*x = GetOrderListReq{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderListReq) ProtoMessage() {}

func (x *GetOrderListReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderListReq.ProtoReflect.Descriptor instead.
func (*GetOrderListReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *GetOrderListReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetOrderListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderInfo           `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderListResp) Reset() {
	*x = GetOrderListResp{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderListResp) ProtoMessage() {}

func (x *GetOrderListResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderListResp.ProtoReflect.Descriptor instead.
func (*GetOrderListResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *GetOrderListResp) GetOrders() []*OrderInfo {
	if x != nil {
		return x.Orders
	}
	return nil
}

type CancelOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderReq) Reset() {
	*x = CancelOrderReq{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderReq) ProtoMessage() {}

func (x *CancelOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderReq.ProtoReflect.Descriptor instead.
func (*CancelOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *CancelOrderReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type CancelOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResp) Reset() {
	*x = CancelOrderResp{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResp) ProtoMessage() {}

func (x *CancelOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResp.ProtoReflect.Descriptor instead.
func (*CancelOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

func (x *CancelOrderResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\"\xe7\x01\n" +
	"\tOrderInfo\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\x18\n" +
	"\aeventId\x18\x02 \x01(\x04R\aeventId\x12\x16\n" +
	"\x06showId\x18\x03 \x01(\rR\x06showId\x12\"\n" +
	"\fticketTypeId\x18\x04 \x01(\rR\fticketTypeId\x12\x18\n" +
	"\aorderNo\x18\x05 \x01(\tR\aorderNo\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\x12\x1e\n" +
	"\n" +
	"totalPrice\x18\a \x01(\x01R\n" +
	"totalPrice\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"\xba\x01\n" +
	"\x0eCreateOrderReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\x18\n" +
	"\aeventId\x18\x02 \x01(\x04R\aeventId\x12\x16\n" +
	"\x06showId\x18\x03 \x01(\rR\x06showId\x12\"\n" +
	"\fticketTypeId\x18\x04 \x01(\rR\fticketTypeId\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12\x1e\n" +
	"\n" +
	"totalPrice\x18\x06 \x01(\x01R\n" +
	"totalPrice\"9\n" +
	"\x0fCreateOrderResp\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.order.OrderInfoR\x05order\"C\n" +
	"\x0fUpdateStatusReq\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\",\n" +
	"\x10UpdateStatusResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x0eDeleteOrderReq\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\tR\aorderNo\"+\n" +
	"\x0fDeleteOrderResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\x0eUpdateOrderReq\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\tR\aorderNo\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"9\n" +
	"\x0fUpdateOrderResp\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.order.OrderInfoR\x05order\"'\n" +
	"\vGetOrderReq\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\tR\aorderNo\"6\n" +
	"\fGetOrderResp\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.order.OrderInfoR\x05order\")\n" +
	"\x0fGetOrderListReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\"<\n" +
	"\x10GetOrderListResp\x12(\n" +
	"\x06orders\x18\x01 \x03(\v2\x10.order.OrderInfoR\x06orders\"*\n" +
	"\x0eCancelOrderReq\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\tR\aorderNo\"+\n" +
	"\x0fCancelOrderResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xbb\x03\n" +
	"\x05Order\x12<\n" +
	"\vCreateOrder\x12\x15.order.CreateOrderReq\x1a\x16.order.CreateOrderResp\x12D\n" +
	"\x11UpdateOrderStatus\x12\x16.order.UpdateStatusReq\x1a\x17.order.UpdateStatusResp\x12<\n" +
	"\vDeleteOrder\x12\x15.order.DeleteOrderReq\x1a\x16.order.DeleteOrderResp\x12<\n" +
	"\vUpdateOrder\x12\x15.order.UpdateOrderReq\x1a\x16.order.UpdateOrderResp\x123\n" +
	"\bGetOrder\x12\x12.order.GetOrderReq\x1a\x13.order.GetOrderResp\x12?\n" +
	"\fGetOrderList\x12\x16.order.GetOrderListReq\x1a\x17.order.GetOrderListResp\x12<\n" +
	"\vCancelOrder\x12\x15.order.CancelOrderReq\x1a\x16.order.CancelOrderRespB\tZ\a./orderb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_order_proto_goTypes = []any{
	(*OrderInfo)(nil),        // 0: order.OrderInfo
	(*CreateOrderReq)(nil),   // 1: order.CreateOrderReq
	(*CreateOrderResp)(nil),  // 2: order.CreateOrderResp
	(*UpdateStatusReq)(nil),  // 3: order.UpdateStatusReq
	(*UpdateStatusResp)(nil), // 4: order.UpdateStatusResp
	(*DeleteOrderReq)(nil),   // 5: order.DeleteOrderReq
	(*DeleteOrderResp)(nil),  // 6: order.DeleteOrderResp
	(*UpdateOrderReq)(nil),   // 7: order.UpdateOrderReq
	(*UpdateOrderResp)(nil),  // 8: order.UpdateOrderResp
	(*GetOrderReq)(nil),      // 9: order.GetOrderReq
	(*GetOrderResp)(nil),     // 10: order.GetOrderResp
	(*GetOrderListReq)(nil),  // 11: order.GetOrderListReq
	(*GetOrderListResp)(nil), // 12: order.GetOrderListResp
	(*CancelOrderReq)(nil),   // 13: order.CancelOrderReq
	(*CancelOrderResp)(nil),  // 14: order.CancelOrderResp
}
var file_order_proto_depIdxs = []int32{
	0,  // 0: order.CreateOrderResp.order:type_name -> order.OrderInfo
	0,  // 1: order.UpdateOrderResp.order:type_name -> order.OrderInfo
	0,  // 2: order.GetOrderResp.order:type_name -> order.OrderInfo
	0,  // 3: order.GetOrderListResp.orders:type_name -> order.OrderInfo
	1,  // 4: order.Order.CreateOrder:input_type -> order.CreateOrderReq
	3,  // 5: order.Order.UpdateOrderStatus:input_type -> order.UpdateStatusReq
	5,  // 6: order.Order.DeleteOrder:input_type -> order.DeleteOrderReq
	7,  // 7: order.Order.UpdateOrder:input_type -> order.UpdateOrderReq
	9,  // 8: order.Order.GetOrder:input_type -> order.GetOrderReq
	11, // 9: order.Order.GetOrderList:input_type -> order.GetOrderListReq
	13, // 10: order.Order.CancelOrder:input_type -> order.CancelOrderReq
	2,  // 11: order.Order.CreateOrder:output_type -> order.CreateOrderResp
	4,  // 12: order.Order.UpdateOrderStatus:output_type -> order.UpdateStatusResp
	6,  // 13: order.Order.DeleteOrder:output_type -> order.DeleteOrderResp
	8,  // 14: order.Order.UpdateOrder:output_type -> order.UpdateOrderResp
	10, // 15: order.Order.GetOrder:output_type -> order.GetOrderResp
	12, // 16: order.Order.GetOrderList:output_type -> order.GetOrderListResp
	14, // 17: order.Order.CancelOrder:output_type -> order.CancelOrderResp
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
