// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateEventReq struct {
	Title       string `json:"title"`
	Description string `json:"description,optional"`
	Location    string `json:"location"`
	CoverImage  string `json:"coverImage,optional"`
	StartTime   string `json:"startTime"`
	EndTime     string `json:"endTime"`
}

type CreateEventResp struct {
}

type CreateShowReq struct {
	EventID   uint   `json:"eventId"`
	Name      string `json:"name"`
	ShowTime  string `json:"showTime"`
	EndTime   string `json:"endTime"`
	SortOrder int    `json:"sortOrder,optional"`
}

type CreateShowResp struct {
}

type CreateTicketTypeReq struct {
	EventID    uint    `json:"eventId"`
	ShowID     uint    `json:"showId"`
	Name       string  `json:"name"`
	Price      float64 `json:"price"`
	Stock      int32   `json:"stock"`
	MaxPerUser int32   `json:"maxPerUser"`
	SortOrder  int32   `json:"sortOrder,optional"`
}

type CreateTicketTypeResp struct {
}

type UpdateEventReq struct {
	EventID     uint   `json:"eventId"`
	Title       string `json:"title,optional"`
	Description string `json:"description,optional"`
	Location    string `json:"location,optional"`
	CoverImage  string `json:"coverImage,optional"`
	StartTime   string `json:"startTime,optional"`
	EndTime     string `json:"endTime,optional"`
}

type UpdateEventResp struct {
}

type UpdateEventStatusReq struct {
	EventID uint   `json:"eventId"`
	Status  string `json:"status"`
}

type UpdateEventStatusResp struct {
}

type UpdateShowReq struct {
	ShowID    uint   `json:"showId"`
	Name      string `json:"name,optional"`
	ShowTime  string `json:"showTime,optional"`
	EndTime   string `json:"endTime,optional"`
	Status    string `json:"status,optional"`
	SortOrder int    `json:"sortOrder,optional"`
}

type UpdateShowResp struct {
}

type UpdateShowStatusReq struct {
	ShowID uint   `json:"showId"`
	Status string `json:"status"`
}

type UpdateShowStatusResp struct {
}

type UpdateTicketTypeReq struct {
	TicketTypeID uint    `json:"ticketTypeId"`
	Name         string  `json:"name,optional"`
	Price        float64 `json:"price,optional"`
	Stock        int32   `json:"stock,optional"`
	MaxPerUser   int32   `json:"maxPerUser,optional"`
	SortOrder    int     `json:"sortOrder,optional"`
}

type UpdateTicketTypeResp struct {
}

type UpdateTicketTypeStatusReq struct {
	TicketTypeID uint   `json:"ticketTypeId"`
	Status       string `json:"status"`
}

type UpdateTicketTypeStatusResp struct {
}
