// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CommonResp struct {
	Message string `json:"message"`
}

type LoginReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Phone    string `json:"phone,optional"`
	Gender   uint8  `json:"gender,optional"`
}

type RegisterResp struct {
	Message string `json:"message"`
}

type UpdateProfileReq struct {
	Email       string `json:"email,optional"`
	Phone       string `json:"phone,optional"`
	Gender      uint8  `json:"gender,optional"`
	Username    string `json:"username,optional"`
	OldPassword string `json:"oldPassword,optional"`
	NewPassword string `json:"newPassword,optional"`
}

type UserProfileResp struct {
	UserId   string `json:"userid"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Gender   string `json:"gender"`
	Role     string `json:"role"`
}
