// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	admininventory "Ticket/app/inventory/inventory-api/internal/handler/admin/inventory"
	inventory "Ticket/app/inventory/inventory-api/internal/handler/inventory"
	"Ticket/app/inventory/inventory-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/inventory/stock",
				Handler: admininventory.UpdateStockHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.AdminAuth.AccessSecret),
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/stock/:ticketTypeId",
				Handler: inventory.GetStockHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/inventory"),
	)
}
