// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ticket.proto

package server

import (
	"context"

	"Ticket/app/ticket/ticket-rpc/internal/logic"
	"Ticket/app/ticket/ticket-rpc/internal/svc"
	"Ticket/app/ticket/ticket-rpc/ticket"
)

type TicketServer struct {
	svcCtx *svc.ServiceContext
	ticket.UnimplementedTicketServer
}

func NewTicketServer(svcCtx *svc.ServiceContext) *TicketServer {
	return &TicketServer{
		svcCtx: svcCtx,
	}
}

// 出票（支付成功后调用）
func (s *TicketServer) CreateTicket(ctx context.Context, in *ticket.CreateTicketReq) (*ticket.CommonResp, error) {
	l := logic.NewCreateTicketLogic(ctx, s.svcCtx)
	return l.CreateTicket(in)
}

// 查询票详情
func (s *TicketServer) GetTicket(ctx context.Context, in *ticket.GetTicketReq) (*ticket.TicketInfo, error) {
	l := logic.NewGetTicketLogic(ctx, s.svcCtx)
	return l.GetTicket(in)
}

// 我的票（分页）
func (s *TicketServer) ListUserTickets(ctx context.Context, in *ticket.ListUserTicketsReq) (*ticket.ListUserTicketsResp, error) {
	l := logic.NewListUserTicketsLogic(ctx, s.svcCtx)
	return l.ListUserTickets(in)
}

// 验票（扫码）
func (s *TicketServer) VerifyTicket(ctx context.Context, in *ticket.VerifyTicketReq) (*ticket.CommonResp, error) {
	l := logic.NewVerifyTicketLogic(ctx, s.svcCtx)
	return l.VerifyTicket(in)
}

// 退票
func (s *TicketServer) RefundTicket(ctx context.Context, in *ticket.RefundTicketReq) (*ticket.CommonResp, error) {
	l := logic.NewRefundTicketLogic(ctx, s.svcCtx)
	return l.RefundTicket(in)
}

// 转赠
func (s *TicketServer) TransferTicket(ctx context.Context, in *ticket.TransferTicketReq) (*ticket.CommonResp, error) {
	l := logic.NewTransferTicketLogic(ctx, s.svcCtx)
	return l.TransferTicket(in)
}

// 管理员查看某活动所有票
func (s *TicketServer) ListEventTickets(ctx context.Context, in *ticket.ListEventTicketsReq) (*ticket.ListEventTicketsResp, error) {
	l := logic.NewListEventTicketsLogic(ctx, s.svcCtx)
	return l.ListEventTickets(in)
}
