// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用返回
type CommonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	mi := &file_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommonResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 初始化库存（创建票种后调用）
type InitStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketTypeId  uint64                 `protobuf:"varint,1,opt,name=ticketTypeId,proto3" json:"ticketTypeId,omitempty"`
	Stock         int32                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitStockReq) Reset() {
	*x = InitStockReq{}
	mi := &file_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitStockReq) ProtoMessage() {}

func (x *InitStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitStockReq.ProtoReflect.Descriptor instead.
func (*InitStockReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *InitStockReq) GetTicketTypeId() uint64 {
	if x != nil {
		return x.TicketTypeId
	}
	return 0
}

func (x *InitStockReq) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

// 查询库存
type GetStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketTypeId  uint64                 `protobuf:"varint,1,opt,name=ticketTypeId,proto3" json:"ticketTypeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockReq) Reset() {
	*x = GetStockReq{}
	mi := &file_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockReq) ProtoMessage() {}

func (x *GetStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockReq.ProtoReflect.Descriptor instead.
func (*GetStockReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetStockReq) GetTicketTypeId() uint64 {
	if x != nil {
		return x.TicketTypeId
	}
	return 0
}

type GetStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TicketTypeId  uint64                 `protobuf:"varint,3,opt,name=ticketTypeId,proto3" json:"ticketTypeId,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockResp) Reset() {
	*x = GetStockResp{}
	mi := &file_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockResp) ProtoMessage() {}

func (x *GetStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockResp.ProtoReflect.Descriptor instead.
func (*GetStockResp) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *GetStockResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetStockResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetStockResp) GetTicketTypeId() uint64 {
	if x != nil {
		return x.TicketTypeId
	}
	return 0
}

func (x *GetStockResp) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

// 扣库存
type DeductStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketTypeId  uint64                 `protobuf:"varint,1,opt,name=ticketTypeId,proto3" json:"ticketTypeId,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockReq) Reset() {
	*x = DeductStockReq{}
	mi := &file_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockReq) ProtoMessage() {}

func (x *DeductStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockReq.ProtoReflect.Descriptor instead.
func (*DeductStockReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *DeductStockReq) GetTicketTypeId() uint64 {
	if x != nil {
		return x.TicketTypeId
	}
	return 0
}

func (x *DeductStockReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type DeductStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RemainStock   int32                  `protobuf:"varint,3,opt,name=remainStock,proto3" json:"remainStock,omitempty"` // 剩余库存
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockResp) Reset() {
	*x = DeductStockResp{}
	mi := &file_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockResp) ProtoMessage() {}

func (x *DeductStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockResp.ProtoReflect.Descriptor instead.
func (*DeductStockResp) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *DeductStockResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeductStockResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeductStockResp) GetRemainStock() int32 {
	if x != nil {
		return x.RemainStock
	}
	return 0
}

// 回滚库存
type ReleaseStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketTypeId  uint64                 `protobuf:"varint,1,opt,name=ticketTypeId,proto3" json:"ticketTypeId,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockReq) Reset() {
	*x = ReleaseStockReq{}
	mi := &file_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockReq) ProtoMessage() {}

func (x *ReleaseStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockReq.ProtoReflect.Descriptor instead.
func (*ReleaseStockReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseStockReq) GetTicketTypeId() uint64 {
	if x != nil {
		return x.TicketTypeId
	}
	return 0
}

func (x *ReleaseStockReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReleaseStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RemainStock   int32                  `protobuf:"varint,3,opt,name=remainStock,proto3" json:"remainStock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockResp) Reset() {
	*x = ReleaseStockResp{}
	mi := &file_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockResp) ProtoMessage() {}

func (x *ReleaseStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockResp.ProtoReflect.Descriptor instead.
func (*ReleaseStockResp) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseStockResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseStockResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReleaseStockResp) GetRemainStock() int32 {
	if x != nil {
		return x.RemainStock
	}
	return 0
}

// 管理员修改库存
type UpdateStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketTypeId  uint64                 `protobuf:"varint,1,opt,name=ticketTypeId,proto3" json:"ticketTypeId,omitempty"`
	Stock         int32                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockReq) Reset() {
	*x = UpdateStockReq{}
	mi := &file_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockReq) ProtoMessage() {}

func (x *UpdateStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockReq.ProtoReflect.Descriptor instead.
func (*UpdateStockReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateStockReq) GetTicketTypeId() uint64 {
	if x != nil {
		return x.TicketTypeId
	}
	return 0
}

func (x *UpdateStockReq) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

var File_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_rawDesc = "" +
	"\n" +
	"\x0finventory.proto\x12\tinventory\"@\n" +
	"\n" +
	"CommonResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\fInitStockReq\x12\"\n" +
	"\fticketTypeId\x18\x01 \x01(\x04R\fticketTypeId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x05R\x05stock\"1\n" +
	"\vGetStockReq\x12\"\n" +
	"\fticketTypeId\x18\x01 \x01(\x04R\fticketTypeId\"|\n" +
	"\fGetStockResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\fticketTypeId\x18\x03 \x01(\x04R\fticketTypeId\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\"P\n" +
	"\x0eDeductStockReq\x12\"\n" +
	"\fticketTypeId\x18\x01 \x01(\x04R\fticketTypeId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"g\n" +
	"\x0fDeductStockResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\vremainStock\x18\x03 \x01(\x05R\vremainStock\"Q\n" +
	"\x0fReleaseStockReq\x12\"\n" +
	"\fticketTypeId\x18\x01 \x01(\x04R\fticketTypeId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"h\n" +
	"\x10ReleaseStockResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\vremainStock\x18\x03 \x01(\x05R\vremainStock\"J\n" +
	"\x0eUpdateStockReq\x12\"\n" +
	"\fticketTypeId\x18\x01 \x01(\x04R\fticketTypeId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x05R\x05stock2\xd5\x02\n" +
	"\tInventory\x12;\n" +
	"\tInitStock\x12\x17.inventory.InitStockReq\x1a\x15.inventory.CommonResp\x12;\n" +
	"\bGetStock\x12\x16.inventory.GetStockReq\x1a\x17.inventory.GetStockResp\x12D\n" +
	"\vDeductStock\x12\x19.inventory.DeductStockReq\x1a\x1a.inventory.DeductStockResp\x12G\n" +
	"\fReleaseStock\x12\x1a.inventory.ReleaseStockReq\x1a\x1b.inventory.ReleaseStockResp\x12?\n" +
	"\vUpdateStock\x12\x19.inventory.UpdateStockReq\x1a\x15.inventory.CommonRespB\rZ\v./inventoryb\x06proto3"

var (
	file_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_rawDescData []byte
)

func file_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_rawDescData
}

var file_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_inventory_proto_goTypes = []any{
	(*CommonResp)(nil),       // 0: inventory.CommonResp
	(*InitStockReq)(nil),     // 1: inventory.InitStockReq
	(*GetStockReq)(nil),      // 2: inventory.GetStockReq
	(*GetStockResp)(nil),     // 3: inventory.GetStockResp
	(*DeductStockReq)(nil),   // 4: inventory.DeductStockReq
	(*DeductStockResp)(nil),  // 5: inventory.DeductStockResp
	(*ReleaseStockReq)(nil),  // 6: inventory.ReleaseStockReq
	(*ReleaseStockResp)(nil), // 7: inventory.ReleaseStockResp
	(*UpdateStockReq)(nil),   // 8: inventory.UpdateStockReq
}
var file_inventory_proto_depIdxs = []int32{
	1, // 0: inventory.Inventory.InitStock:input_type -> inventory.InitStockReq
	2, // 1: inventory.Inventory.GetStock:input_type -> inventory.GetStockReq
	4, // 2: inventory.Inventory.DeductStock:input_type -> inventory.DeductStockReq
	6, // 3: inventory.Inventory.ReleaseStock:input_type -> inventory.ReleaseStockReq
	8, // 4: inventory.Inventory.UpdateStock:input_type -> inventory.UpdateStockReq
	0, // 5: inventory.Inventory.InitStock:output_type -> inventory.CommonResp
	3, // 6: inventory.Inventory.GetStock:output_type -> inventory.GetStockResp
	5, // 7: inventory.Inventory.DeductStock:output_type -> inventory.DeductStockResp
	7, // 8: inventory.Inventory.ReleaseStock:output_type -> inventory.ReleaseStockResp
	0, // 9: inventory.Inventory.UpdateStock:output_type -> inventory.CommonResp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inventory_proto_init() }
func file_inventory_proto_init() {
	if File_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto = out.File
	file_inventory_proto_goTypes = nil
	file_inventory_proto_depIdxs = nil
}
