// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CheckTicketReq struct {
	TicketId uint64 `json:"ticketId"`
}

type CommonResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type GetTicketReq struct {
	TicketId uint64 `path:"ticketId"`
}

type GetTicketResp struct {
	Code           int64   `json:"code"`
	Msg            string  `json:"msg"`
	TicketId       uint64  `json:"ticketId"`
	OrderNo        string  `json:"orderNo"`
	EventId        uint64  `json:"eventId"`
	ShowId         uint64  `json:"showId"`
	TicketTypeId   uint64  `json:"ticketTypeId"`
	Quantity       int     `json:"quantity"`
	TotalPrice     float64 `json:"totalPrice"`
	Status         string  `json:"status"`
	QrCode         string  `json:"qrCode"`
	DiscountCode   string  `json:"discountCode"`
	RealName       string  `json:"realName"`
	IdCard         string  `json:"idCard"`
	Phone          string  `json:"phone"`
	TransferredTo  uint64  `json:"transferredTo"`
	TransferStatus string  `json:"transferStatus"`
	CreatedAt      string  `json:"createdAt"`
	UpdatedAt      string  `json:"updatedAt"`
}

type IssueTicketReq struct {
	OrderNo string `json:"orderNo"`
}

type ListTicketReq struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Status   string `form:"status,optional"`
}

type ListTicketResp struct {
	Code  int64        `json:"code"`
	Msg   string       `json:"msg"`
	Total int64        `json:"total"`
	List  []TicketInfo `json:"list"`
}

type RefundTicketReq struct {
	TicketId uint64 `json:"ticketId"`
}

type TicketInfo struct {
	TicketId       uint64  `json:"ticketId"`
	OrderNo        string  `json:"orderNo"`
	EventId        uint64  `json:"eventId"`
	ShowId         uint64  `json:"showId"`
	TicketTypeId   uint64  `json:"ticketTypeId"`
	Quantity       int     `json:"quantity"`
	TotalPrice     float64 `json:"totalPrice"`
	Status         string  `json:"status"`
	RealName       string  `json:"realName"`
	Phone          string  `json:"phone"`
	TransferStatus string  `json:"transferStatus"`
	CreatedAt      string  `json:"createdAt"`
}
