// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: event.proto

package eventclient

import (
	"context"

	"Ticket/app/event/event-rpc/event"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResp            = event.CommonResp
	CreateEventReq        = event.CreateEventReq
	CreateShowReq         = event.CreateShowReq
	CreateTicketTypeReq   = event.CreateTicketTypeReq
	Empty                 = event.Empty
	EventInfo             = event.EventInfo
	GetEventListReq       = event.GetEventListReq
	GetEventListResp      = event.GetEventListResp
	GetEventReq           = event.GetEventReq
	GetEventResp          = event.GetEventResp
	GetShowListReq        = event.GetShowListReq
	GetShowListResp       = event.GetShowListResp
	GetShowReq            = event.GetShowReq
	GetShowResp           = event.GetShowResp
	GetTicketTypeListReq  = event.GetTicketTypeListReq
	GetTicketTypeListResp = event.GetTicketTypeListResp
	GetTicketTypeReq      = event.GetTicketTypeReq
	GetTicketTypeResp     = event.GetTicketTypeResp
	ShowInfo              = event.ShowInfo
	TicketTypeInfo        = event.TicketTypeInfo
	UpdateEventReq        = event.UpdateEventReq
	UpdateEventStatusReq  = event.UpdateEventStatusReq
	UpdateShowReq         = event.UpdateShowReq
	UpdateTicketTypeReq   = event.UpdateTicketTypeReq

	Event interface {
		// 获取活动列表
		GetEventList(ctx context.Context, in *GetEventListReq, opts ...grpc.CallOption) (*GetEventListResp, error)
		// 获取活动详情
		GetEvent(ctx context.Context, in *GetEventReq, opts ...grpc.CallOption) (*GetEventResp, error)
		// 获取活动下所有场次
		GetShowList(ctx context.Context, in *GetShowListReq, opts ...grpc.CallOption) (*GetShowListResp, error)
		// 获取场次详情
		GetShow(ctx context.Context, in *GetShowReq, opts ...grpc.CallOption) (*GetShowResp, error)
		// 获取场次下所有票种
		GetTicketTypeList(ctx context.Context, in *GetTicketTypeListReq, opts ...grpc.CallOption) (*GetTicketTypeListResp, error)
		// 获取票种详情（Order 创建订单主要调用）
		GetTicketType(ctx context.Context, in *GetTicketTypeReq, opts ...grpc.CallOption) (*GetTicketTypeResp, error)
		// 创建活动
		CreateEvent(ctx context.Context, in *CreateEventReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 修改活动
		UpdateEvent(ctx context.Context, in *UpdateEventReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 修改活动状态（draft、ready、selling、closed）
		UpdateEventStatus(ctx context.Context, in *UpdateEventStatusReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 创建场次
		CreateShow(ctx context.Context, in *CreateShowReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 修改场次
		UpdateShow(ctx context.Context, in *UpdateShowReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 创建票种
		CreateTicketType(ctx context.Context, in *CreateTicketTypeReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 修改票种
		UpdateTicketType(ctx context.Context, in *UpdateTicketTypeReq, opts ...grpc.CallOption) (*CommonResp, error)
	}

	defaultEvent struct {
		cli zrpc.Client
	}
)

func NewEvent(cli zrpc.Client) Event {
	return &defaultEvent{
		cli: cli,
	}
}

// 获取活动列表
func (m *defaultEvent) GetEventList(ctx context.Context, in *GetEventListReq, opts ...grpc.CallOption) (*GetEventListResp, error) {
	client := event.NewEventClient(m.cli.Conn())
	return client.GetEventList(ctx, in, opts...)
}

// 获取活动详情
func (m *defaultEvent) GetEvent(ctx context.Context, in *GetEventReq, opts ...grpc.CallOption) (*GetEventResp, error) {
	client := event.NewEventClient(m.cli.Conn())
	return client.GetEvent(ctx, in, opts...)
}

// 获取活动下所有场次
func (m *defaultEvent) GetShowList(ctx context.Context, in *GetShowListReq, opts ...grpc.CallOption) (*GetShowListResp, error) {
	client := event.NewEventClient(m.cli.Conn())
	return client.GetShowList(ctx, in, opts...)
}

// 获取场次详情
func (m *defaultEvent) GetShow(ctx context.Context, in *GetShowReq, opts ...grpc.CallOption) (*GetShowResp, error) {
	client := event.NewEventClient(m.cli.Conn())
	return client.GetShow(ctx, in, opts...)
}

// 获取场次下所有票种
func (m *defaultEvent) GetTicketTypeList(ctx context.Context, in *GetTicketTypeListReq, opts ...grpc.CallOption) (*GetTicketTypeListResp, error) {
	client := event.NewEventClient(m.cli.Conn())
	return client.GetTicketTypeList(ctx, in, opts...)
}

// 获取票种详情（Order 创建订单主要调用）
func (m *defaultEvent) GetTicketType(ctx context.Context, in *GetTicketTypeReq, opts ...grpc.CallOption) (*GetTicketTypeResp, error) {
	client := event.NewEventClient(m.cli.Conn())
	return client.GetTicketType(ctx, in, opts...)
}

// 创建活动
func (m *defaultEvent) CreateEvent(ctx context.Context, in *CreateEventReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := event.NewEventClient(m.cli.Conn())
	return client.CreateEvent(ctx, in, opts...)
}

// 修改活动
func (m *defaultEvent) UpdateEvent(ctx context.Context, in *UpdateEventReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := event.NewEventClient(m.cli.Conn())
	return client.UpdateEvent(ctx, in, opts...)
}

// 修改活动状态（draft、ready、selling、closed）
func (m *defaultEvent) UpdateEventStatus(ctx context.Context, in *UpdateEventStatusReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := event.NewEventClient(m.cli.Conn())
	return client.UpdateEventStatus(ctx, in, opts...)
}

// 创建场次
func (m *defaultEvent) CreateShow(ctx context.Context, in *CreateShowReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := event.NewEventClient(m.cli.Conn())
	return client.CreateShow(ctx, in, opts...)
}

// 修改场次
func (m *defaultEvent) UpdateShow(ctx context.Context, in *UpdateShowReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := event.NewEventClient(m.cli.Conn())
	return client.UpdateShow(ctx, in, opts...)
}

// 创建票种
func (m *defaultEvent) CreateTicketType(ctx context.Context, in *CreateTicketTypeReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := event.NewEventClient(m.cli.Conn())
	return client.CreateTicketType(ctx, in, opts...)
}

// 修改票种
func (m *defaultEvent) UpdateTicketType(ctx context.Context, in *UpdateTicketTypeReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := event.NewEventClient(m.cli.Conn())
	return client.UpdateTicketType(ctx, in, opts...)
}
