// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: inventory.proto

package server

import (
	"context"

	"Ticket/app/inventory/inventory-rpc/internal/logic"
	"Ticket/app/inventory/inventory-rpc/internal/svc"
	"Ticket/app/inventory/inventory-rpc/inventory"
)

type InventoryServer struct {
	svcCtx *svc.ServiceContext
	inventory.UnimplementedInventoryServer
}

func NewInventoryServer(svcCtx *svc.ServiceContext) *InventoryServer {
	return &InventoryServer{
		svcCtx: svcCtx,
	}
}

// 初始化库存
func (s *InventoryServer) InitStock(ctx context.Context, in *inventory.InitStockReq) (*inventory.CommonResp, error) {
	l := logic.NewInitStockLogic(ctx, s.svcCtx)
	return l.InitStock(in)
}

// 查询库存
func (s *InventoryServer) GetStock(ctx context.Context, in *inventory.GetStockReq) (*inventory.GetStockResp, error) {
	l := logic.NewGetStockLogic(ctx, s.svcCtx)
	return l.GetStock(in)
}

// 扣库存
func (s *InventoryServer) DeductStock(ctx context.Context, in *inventory.DeductStockReq) (*inventory.DeductStockResp, error) {
	l := logic.NewDeductStockLogic(ctx, s.svcCtx)
	return l.DeductStock(in)
}

// 回滚库存
func (s *InventoryServer) ReleaseStock(ctx context.Context, in *inventory.ReleaseStockReq) (*inventory.ReleaseStockResp, error) {
	l := logic.NewReleaseStockLogic(ctx, s.svcCtx)
	return l.ReleaseStock(in)
}

// 修改库存
func (s *InventoryServer) UpdateStock(ctx context.Context, in *inventory.UpdateStockReq) (*inventory.CommonResp, error) {
	l := logic.NewUpdateStockLogic(ctx, s.svcCtx)
	return l.UpdateStock(in)
}
