// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: event.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommonResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

type EventInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	CoverImage    string                 `protobuf:"bytes,5,opt,name=coverImage,proto3" json:"coverImage,omitempty"`
	StartTime     int64                  `protobuf:"varint,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       int64                  `protobuf:"varint,7,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	TotalStock    int32                  `protobuf:"varint,9,opt,name=totalStock,proto3" json:"totalStock,omitempty"` //只做展示不做扣除，真正扣除确认在lua脚本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventInfo) Reset() {
	*x = EventInfo{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventInfo) ProtoMessage() {}

func (x *EventInfo) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventInfo.ProtoReflect.Descriptor instead.
func (*EventInfo) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *EventInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EventInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EventInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *EventInfo) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *EventInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *EventInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *EventInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EventInfo) GetTotalStock() int32 {
	if x != nil {
		return x.TotalStock
	}
	return 0
}

type GetEventListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventListReq) Reset() {
	*x = GetEventListReq{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventListReq) ProtoMessage() {}

func (x *GetEventListReq) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventListReq.ProtoReflect.Descriptor instead.
func (*GetEventListReq) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

// 获取活动列表
type GetEventListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventInfo           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventListResp) Reset() {
	*x = GetEventListResp{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventListResp) ProtoMessage() {}

func (x *GetEventListResp) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventListResp.ProtoReflect.Descriptor instead.
func (*GetEventListResp) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4}
}

func (x *GetEventListResp) GetEvents() []*EventInfo {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint64                 `protobuf:"varint,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventReq) Reset() {
	*x = GetEventReq{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventReq) ProtoMessage() {}

func (x *GetEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventReq.ProtoReflect.Descriptor instead.
func (*GetEventReq) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{5}
}

func (x *GetEventReq) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type GetEventResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *EventInfo             `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventResp) Reset() {
	*x = GetEventResp{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventResp) ProtoMessage() {}

func (x *GetEventResp) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventResp.ProtoReflect.Descriptor instead.
func (*GetEventResp) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{6}
}

func (x *GetEventResp) GetEvent() *EventInfo {
	if x != nil {
		return x.Event
	}
	return nil
}

// 创建活动
type CreateEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	CoverImage    string                 `protobuf:"bytes,4,opt,name=coverImage,proto3" json:"coverImage,omitempty"`
	StartTime     string                 `protobuf:"bytes,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       string                 `protobuf:"bytes,6,opt,name=endTime,proto3" json:"endTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventReq) Reset() {
	*x = CreateEventReq{}
	mi := &file_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventReq) ProtoMessage() {}

func (x *CreateEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventReq.ProtoReflect.Descriptor instead.
func (*CreateEventReq) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{7}
}

func (x *CreateEventReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEventReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEventReq) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateEventReq) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *CreateEventReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreateEventReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

// 更新活动
type UpdateEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint64                 `protobuf:"varint,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	CoverImage    string                 `protobuf:"bytes,5,opt,name=coverImage,proto3" json:"coverImage,omitempty"`
	StartTime     string                 `protobuf:"bytes,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       string                 `protobuf:"bytes,7,opt,name=endTime,proto3" json:"endTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventReq) Reset() {
	*x = UpdateEventReq{}
	mi := &file_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventReq) ProtoMessage() {}

func (x *UpdateEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventReq.ProtoReflect.Descriptor instead.
func (*UpdateEventReq) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateEventReq) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *UpdateEventReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateEventReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateEventReq) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateEventReq) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *UpdateEventReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *UpdateEventReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

// 更新活动
type UpdateEventStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint64                 `protobuf:"varint,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventStatusReq) Reset() {
	*x = UpdateEventStatusReq{}
	mi := &file_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventStatusReq) ProtoMessage() {}

func (x *UpdateEventStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateEventStatusReq) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateEventStatusReq) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *UpdateEventStatusReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ShowInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       uint64                 `protobuf:"varint,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ShowTime      string                 `protobuf:"bytes,4,opt,name=showTime,proto3" json:"showTime,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	SoldCount     int32                  `protobuf:"varint,7,opt,name=soldCount,proto3" json:"soldCount,omitempty"` //只做展示不做扣除，真正扣除确认在lua脚本
	SortOrder     int32                  `protobuf:"varint,8,opt,name=sortOrder,proto3" json:"sortOrder,omitempty"`
	Venue         string                 `protobuf:"bytes,9,opt,name=venue,proto3" json:"venue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowInfo) Reset() {
	*x = ShowInfo{}
	mi := &file_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowInfo) ProtoMessage() {}

func (x *ShowInfo) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowInfo.ProtoReflect.Descriptor instead.
func (*ShowInfo) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{10}
}

func (x *ShowInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShowInfo) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ShowInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShowInfo) GetShowTime() string {
	if x != nil {
		return x.ShowTime
	}
	return ""
}

func (x *ShowInfo) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ShowInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ShowInfo) GetSoldCount() int32 {
	if x != nil {
		return x.SoldCount
	}
	return 0
}

func (x *ShowInfo) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *ShowInfo) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

// 获取活动下所有场次
type GetShowListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint64                 `protobuf:"varint,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowListReq) Reset() {
	*x = GetShowListReq{}
	mi := &file_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowListReq) ProtoMessage() {}

func (x *GetShowListReq) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowListReq.ProtoReflect.Descriptor instead.
func (*GetShowListReq) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{11}
}

func (x *GetShowListReq) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type GetShowListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shows         []*ShowInfo            `protobuf:"bytes,1,rep,name=shows,proto3" json:"shows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowListResp) Reset() {
	*x = GetShowListResp{}
	mi := &file_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowListResp) ProtoMessage() {}

func (x *GetShowListResp) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowListResp.ProtoReflect.Descriptor instead.
func (*GetShowListResp) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{12}
}

func (x *GetShowListResp) GetShows() []*ShowInfo {
	if x != nil {
		return x.Shows
	}
	return nil
}

// 获取某个场次详情
type GetShowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowId        uint64                 `protobuf:"varint,1,opt,name=showId,proto3" json:"showId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowReq) Reset() {
	*x = GetShowReq{}
	mi := &file_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowReq) ProtoMessage() {}

func (x *GetShowReq) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowReq.ProtoReflect.Descriptor instead.
func (*GetShowReq) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{13}
}

func (x *GetShowReq) GetShowId() uint64 {
	if x != nil {
		return x.ShowId
	}
	return 0
}

type GetShowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Show          *ShowInfo              `protobuf:"bytes,1,opt,name=show,proto3" json:"show,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowResp) Reset() {
	*x = GetShowResp{}
	mi := &file_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowResp) ProtoMessage() {}

func (x *GetShowResp) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowResp.ProtoReflect.Descriptor instead.
func (*GetShowResp) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{14}
}

func (x *GetShowResp) GetShow() *ShowInfo {
	if x != nil {
		return x.Show
	}
	return nil
}

// 创建场次
type CreateShowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint64                 `protobuf:"varint,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ShowTime      string                 `protobuf:"bytes,3,opt,name=showTime,proto3" json:"showTime,omitempty"`
	EndTime       string                 `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	SortOrder     int32                  `protobuf:"varint,5,opt,name=sortOrder,proto3" json:"sortOrder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShowReq) Reset() {
	*x = CreateShowReq{}
	mi := &file_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShowReq) ProtoMessage() {}

func (x *CreateShowReq) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShowReq.ProtoReflect.Descriptor instead.
func (*CreateShowReq) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{15}
}

func (x *CreateShowReq) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateShowReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateShowReq) GetShowTime() string {
	if x != nil {
		return x.ShowTime
	}
	return ""
}

func (x *CreateShowReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreateShowReq) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

// 更新场次
type UpdateShowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowId        uint64                 `protobuf:"varint,1,opt,name=showId,proto3" json:"showId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ShowTime      string                 `protobuf:"bytes,3,opt,name=showTime,proto3" json:"showTime,omitempty"`
	EndTime       string                 `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Venue         string                 `protobuf:"bytes,6,opt,name=venue,proto3" json:"venue,omitempty"`
	SortOrder     int32                  `protobuf:"varint,7,opt,name=sortOrder,proto3" json:"sortOrder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShowReq) Reset() {
	*x = UpdateShowReq{}
	mi := &file_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShowReq) ProtoMessage() {}

func (x *UpdateShowReq) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShowReq.ProtoReflect.Descriptor instead.
func (*UpdateShowReq) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateShowReq) GetShowId() uint64 {
	if x != nil {
		return x.ShowId
	}
	return 0
}

func (x *UpdateShowReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateShowReq) GetShowTime() string {
	if x != nil {
		return x.ShowTime
	}
	return ""
}

func (x *UpdateShowReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *UpdateShowReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateShowReq) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *UpdateShowReq) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type TicketTypeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       uint64                 `protobuf:"varint,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	ShowId        uint64                 `protobuf:"varint,3,opt,name=showId,proto3" json:"showId,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	MaxPerUser    int32                  `protobuf:"varint,7,opt,name=maxPerUser,proto3" json:"maxPerUser,omitempty"`
	SortOrder     int32                  `protobuf:"varint,8,opt,name=sortOrder,proto3" json:"sortOrder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketTypeInfo) Reset() {
	*x = TicketTypeInfo{}
	mi := &file_event_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketTypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketTypeInfo) ProtoMessage() {}

func (x *TicketTypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketTypeInfo.ProtoReflect.Descriptor instead.
func (*TicketTypeInfo) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{17}
}

func (x *TicketTypeInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TicketTypeInfo) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *TicketTypeInfo) GetShowId() uint64 {
	if x != nil {
		return x.ShowId
	}
	return 0
}

func (x *TicketTypeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TicketTypeInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TicketTypeInfo) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *TicketTypeInfo) GetMaxPerUser() int32 {
	if x != nil {
		return x.MaxPerUser
	}
	return 0
}

func (x *TicketTypeInfo) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

// 获取场次下所有票种
type GetTicketTypeListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowId        uint64                 `protobuf:"varint,1,opt,name=showId,proto3" json:"showId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketTypeListReq) Reset() {
	*x = GetTicketTypeListReq{}
	mi := &file_event_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketTypeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketTypeListReq) ProtoMessage() {}

func (x *GetTicketTypeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketTypeListReq.ProtoReflect.Descriptor instead.
func (*GetTicketTypeListReq) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{18}
}

func (x *GetTicketTypeListReq) GetShowId() uint64 {
	if x != nil {
		return x.ShowId
	}
	return 0
}

type GetTicketTypeListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketTypes   []*TicketTypeInfo      `protobuf:"bytes,1,rep,name=ticketTypes,proto3" json:"ticketTypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketTypeListResp) Reset() {
	*x = GetTicketTypeListResp{}
	mi := &file_event_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketTypeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketTypeListResp) ProtoMessage() {}

func (x *GetTicketTypeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketTypeListResp.ProtoReflect.Descriptor instead.
func (*GetTicketTypeListResp) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{19}
}

func (x *GetTicketTypeListResp) GetTicketTypes() []*TicketTypeInfo {
	if x != nil {
		return x.TicketTypes
	}
	return nil
}

// 获取票种详情
type GetTicketTypeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketTypeId  uint64                 `protobuf:"varint,1,opt,name=ticketTypeId,proto3" json:"ticketTypeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketTypeReq) Reset() {
	*x = GetTicketTypeReq{}
	mi := &file_event_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketTypeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketTypeReq) ProtoMessage() {}

func (x *GetTicketTypeReq) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketTypeReq.ProtoReflect.Descriptor instead.
func (*GetTicketTypeReq) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{20}
}

func (x *GetTicketTypeReq) GetTicketTypeId() uint64 {
	if x != nil {
		return x.TicketTypeId
	}
	return 0
}

type GetTicketTypeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketType    *TicketTypeInfo        `protobuf:"bytes,1,opt,name=ticketType,proto3" json:"ticketType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketTypeResp) Reset() {
	*x = GetTicketTypeResp{}
	mi := &file_event_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketTypeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketTypeResp) ProtoMessage() {}

func (x *GetTicketTypeResp) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketTypeResp.ProtoReflect.Descriptor instead.
func (*GetTicketTypeResp) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{21}
}

func (x *GetTicketTypeResp) GetTicketType() *TicketTypeInfo {
	if x != nil {
		return x.TicketType
	}
	return nil
}

// 创建某个票种
type CreateTicketTypeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint64                 `protobuf:"varint,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	ShowId        uint64                 `protobuf:"varint,2,opt,name=showId,proto3" json:"showId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	MaxPerUser    int32                  `protobuf:"varint,6,opt,name=maxPerUser,proto3" json:"maxPerUser,omitempty"`
	SortOrder     int32                  `protobuf:"varint,7,opt,name=sortOrder,proto3" json:"sortOrder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketTypeReq) Reset() {
	*x = CreateTicketTypeReq{}
	mi := &file_event_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketTypeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketTypeReq) ProtoMessage() {}

func (x *CreateTicketTypeReq) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketTypeReq.ProtoReflect.Descriptor instead.
func (*CreateTicketTypeReq) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{22}
}

func (x *CreateTicketTypeReq) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateTicketTypeReq) GetShowId() uint64 {
	if x != nil {
		return x.ShowId
	}
	return 0
}

func (x *CreateTicketTypeReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTicketTypeReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateTicketTypeReq) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateTicketTypeReq) GetMaxPerUser() int32 {
	if x != nil {
		return x.MaxPerUser
	}
	return 0
}

func (x *CreateTicketTypeReq) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

// 更新票种
type UpdateTicketTypeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketTypeId  uint64                 `protobuf:"varint,1,opt,name=ticketTypeId,proto3" json:"ticketTypeId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	MaxPerUser    int32                  `protobuf:"varint,5,opt,name=maxPerUser,proto3" json:"maxPerUser,omitempty"`
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sortOrder,proto3" json:"sortOrder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketTypeReq) Reset() {
	*x = UpdateTicketTypeReq{}
	mi := &file_event_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketTypeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketTypeReq) ProtoMessage() {}

func (x *UpdateTicketTypeReq) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketTypeReq.ProtoReflect.Descriptor instead.
func (*UpdateTicketTypeReq) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateTicketTypeReq) GetTicketTypeId() uint64 {
	if x != nil {
		return x.TicketTypeId
	}
	return 0
}

func (x *UpdateTicketTypeReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTicketTypeReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateTicketTypeReq) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateTicketTypeReq) GetMaxPerUser() int32 {
	if x != nil {
		return x.MaxPerUser
	}
	return 0
}

func (x *UpdateTicketTypeReq) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\x05event\"@\n" +
	"\n" +
	"CommonResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\a\n" +
	"\x05Empty\"\xff\x01\n" +
	"\tEventInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1e\n" +
	"\n" +
	"coverImage\x18\x05 \x01(\tR\n" +
	"coverImage\x12\x1c\n" +
	"\tstartTime\x18\x06 \x01(\x03R\tstartTime\x12\x18\n" +
	"\aendTime\x18\a \x01(\x03R\aendTime\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"totalStock\x18\t \x01(\x05R\n" +
	"totalStock\"\x11\n" +
	"\x0fGetEventListReq\"<\n" +
	"\x10GetEventListResp\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.event.EventInfoR\x06events\"'\n" +
	"\vGetEventReq\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\x04R\aeventId\"6\n" +
	"\fGetEventResp\x12&\n" +
	"\x05event\x18\x01 \x01(\v2\x10.event.EventInfoR\x05event\"\xbc\x01\n" +
	"\x0eCreateEventReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1e\n" +
	"\n" +
	"coverImage\x18\x04 \x01(\tR\n" +
	"coverImage\x12\x1c\n" +
	"\tstartTime\x18\x05 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\x06 \x01(\tR\aendTime\"\xd6\x01\n" +
	"\x0eUpdateEventReq\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\x04R\aeventId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1e\n" +
	"\n" +
	"coverImage\x18\x05 \x01(\tR\n" +
	"coverImage\x12\x1c\n" +
	"\tstartTime\x18\x06 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\a \x01(\tR\aendTime\"H\n" +
	"\x14UpdateEventStatusReq\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\x04R\aeventId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xe8\x01\n" +
	"\bShowInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aeventId\x18\x02 \x01(\x04R\aeventId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bshowTime\x18\x04 \x01(\tR\bshowTime\x12\x18\n" +
	"\aendTime\x18\x05 \x01(\tR\aendTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1c\n" +
	"\tsoldCount\x18\a \x01(\x05R\tsoldCount\x12\x1c\n" +
	"\tsortOrder\x18\b \x01(\x05R\tsortOrder\x12\x14\n" +
	"\x05venue\x18\t \x01(\tR\x05venue\"*\n" +
	"\x0eGetShowListReq\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\x04R\aeventId\"8\n" +
	"\x0fGetShowListResp\x12%\n" +
	"\x05shows\x18\x01 \x03(\v2\x0f.event.ShowInfoR\x05shows\"$\n" +
	"\n" +
	"GetShowReq\x12\x16\n" +
	"\x06showId\x18\x01 \x01(\x04R\x06showId\"2\n" +
	"\vGetShowResp\x12#\n" +
	"\x04show\x18\x01 \x01(\v2\x0f.event.ShowInfoR\x04show\"\x91\x01\n" +
	"\rCreateShowReq\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\x04R\aeventId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bshowTime\x18\x03 \x01(\tR\bshowTime\x12\x18\n" +
	"\aendTime\x18\x04 \x01(\tR\aendTime\x12\x1c\n" +
	"\tsortOrder\x18\x05 \x01(\x05R\tsortOrder\"\xbd\x01\n" +
	"\rUpdateShowReq\x12\x16\n" +
	"\x06showId\x18\x01 \x01(\x04R\x06showId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bshowTime\x18\x03 \x01(\tR\bshowTime\x12\x18\n" +
	"\aendTime\x18\x04 \x01(\tR\aendTime\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05venue\x18\x06 \x01(\tR\x05venue\x12\x1c\n" +
	"\tsortOrder\x18\a \x01(\x05R\tsortOrder\"\xd0\x01\n" +
	"\x0eTicketTypeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aeventId\x18\x02 \x01(\x04R\aeventId\x12\x16\n" +
	"\x06showId\x18\x03 \x01(\x04R\x06showId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x05R\x05stock\x12\x1e\n" +
	"\n" +
	"maxPerUser\x18\a \x01(\x05R\n" +
	"maxPerUser\x12\x1c\n" +
	"\tsortOrder\x18\b \x01(\x05R\tsortOrder\".\n" +
	"\x14GetTicketTypeListReq\x12\x16\n" +
	"\x06showId\x18\x01 \x01(\x04R\x06showId\"P\n" +
	"\x15GetTicketTypeListResp\x127\n" +
	"\vticketTypes\x18\x01 \x03(\v2\x15.event.TicketTypeInfoR\vticketTypes\"6\n" +
	"\x10GetTicketTypeReq\x12\"\n" +
	"\fticketTypeId\x18\x01 \x01(\x04R\fticketTypeId\"J\n" +
	"\x11GetTicketTypeResp\x125\n" +
	"\n" +
	"ticketType\x18\x01 \x01(\v2\x15.event.TicketTypeInfoR\n" +
	"ticketType\"\xc5\x01\n" +
	"\x13CreateTicketTypeReq\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\x04R\aeventId\x12\x16\n" +
	"\x06showId\x18\x02 \x01(\x04R\x06showId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\x12\x1e\n" +
	"\n" +
	"maxPerUser\x18\x06 \x01(\x05R\n" +
	"maxPerUser\x12\x1c\n" +
	"\tsortOrder\x18\a \x01(\x05R\tsortOrder\"\xb7\x01\n" +
	"\x13UpdateTicketTypeReq\x12\"\n" +
	"\fticketTypeId\x18\x01 \x01(\x04R\fticketTypeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\x12\x1e\n" +
	"\n" +
	"maxPerUser\x18\x05 \x01(\x05R\n" +
	"maxPerUser\x12\x1c\n" +
	"\tsortOrder\x18\x06 \x01(\x05R\tsortOrder2\xac\x06\n" +
	"\x05Event\x12?\n" +
	"\fGetEventList\x12\x16.event.GetEventListReq\x1a\x17.event.GetEventListResp\x123\n" +
	"\bGetEvent\x12\x12.event.GetEventReq\x1a\x13.event.GetEventResp\x12<\n" +
	"\vGetShowList\x12\x15.event.GetShowListReq\x1a\x16.event.GetShowListResp\x120\n" +
	"\aGetShow\x12\x11.event.GetShowReq\x1a\x12.event.GetShowResp\x12N\n" +
	"\x11GetTicketTypeList\x12\x1b.event.GetTicketTypeListReq\x1a\x1c.event.GetTicketTypeListResp\x12B\n" +
	"\rGetTicketType\x12\x17.event.GetTicketTypeReq\x1a\x18.event.GetTicketTypeResp\x127\n" +
	"\vCreateEvent\x12\x15.event.CreateEventReq\x1a\x11.event.CommonResp\x127\n" +
	"\vUpdateEvent\x12\x15.event.UpdateEventReq\x1a\x11.event.CommonResp\x12C\n" +
	"\x11UpdateEventStatus\x12\x1b.event.UpdateEventStatusReq\x1a\x11.event.CommonResp\x125\n" +
	"\n" +
	"CreateShow\x12\x14.event.CreateShowReq\x1a\x11.event.CommonResp\x125\n" +
	"\n" +
	"UpdateShow\x12\x14.event.UpdateShowReq\x1a\x11.event.CommonResp\x12A\n" +
	"\x10CreateTicketType\x12\x1a.event.CreateTicketTypeReq\x1a\x11.event.CommonResp\x12A\n" +
	"\x10UpdateTicketType\x12\x1a.event.UpdateTicketTypeReq\x1a\x11.event.CommonRespB\tZ\a./eventb\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_event_proto_goTypes = []any{
	(*CommonResp)(nil),            // 0: event.CommonResp
	(*Empty)(nil),                 // 1: event.Empty
	(*EventInfo)(nil),             // 2: event.EventInfo
	(*GetEventListReq)(nil),       // 3: event.GetEventListReq
	(*GetEventListResp)(nil),      // 4: event.GetEventListResp
	(*GetEventReq)(nil),           // 5: event.GetEventReq
	(*GetEventResp)(nil),          // 6: event.GetEventResp
	(*CreateEventReq)(nil),        // 7: event.CreateEventReq
	(*UpdateEventReq)(nil),        // 8: event.UpdateEventReq
	(*UpdateEventStatusReq)(nil),  // 9: event.UpdateEventStatusReq
	(*ShowInfo)(nil),              // 10: event.ShowInfo
	(*GetShowListReq)(nil),        // 11: event.GetShowListReq
	(*GetShowListResp)(nil),       // 12: event.GetShowListResp
	(*GetShowReq)(nil),            // 13: event.GetShowReq
	(*GetShowResp)(nil),           // 14: event.GetShowResp
	(*CreateShowReq)(nil),         // 15: event.CreateShowReq
	(*UpdateShowReq)(nil),         // 16: event.UpdateShowReq
	(*TicketTypeInfo)(nil),        // 17: event.TicketTypeInfo
	(*GetTicketTypeListReq)(nil),  // 18: event.GetTicketTypeListReq
	(*GetTicketTypeListResp)(nil), // 19: event.GetTicketTypeListResp
	(*GetTicketTypeReq)(nil),      // 20: event.GetTicketTypeReq
	(*GetTicketTypeResp)(nil),     // 21: event.GetTicketTypeResp
	(*CreateTicketTypeReq)(nil),   // 22: event.CreateTicketTypeReq
	(*UpdateTicketTypeReq)(nil),   // 23: event.UpdateTicketTypeReq
}
var file_event_proto_depIdxs = []int32{
	2,  // 0: event.GetEventListResp.events:type_name -> event.EventInfo
	2,  // 1: event.GetEventResp.event:type_name -> event.EventInfo
	10, // 2: event.GetShowListResp.shows:type_name -> event.ShowInfo
	10, // 3: event.GetShowResp.show:type_name -> event.ShowInfo
	17, // 4: event.GetTicketTypeListResp.ticketTypes:type_name -> event.TicketTypeInfo
	17, // 5: event.GetTicketTypeResp.ticketType:type_name -> event.TicketTypeInfo
	3,  // 6: event.Event.GetEventList:input_type -> event.GetEventListReq
	5,  // 7: event.Event.GetEvent:input_type -> event.GetEventReq
	11, // 8: event.Event.GetShowList:input_type -> event.GetShowListReq
	13, // 9: event.Event.GetShow:input_type -> event.GetShowReq
	18, // 10: event.Event.GetTicketTypeList:input_type -> event.GetTicketTypeListReq
	20, // 11: event.Event.GetTicketType:input_type -> event.GetTicketTypeReq
	7,  // 12: event.Event.CreateEvent:input_type -> event.CreateEventReq
	8,  // 13: event.Event.UpdateEvent:input_type -> event.UpdateEventReq
	9,  // 14: event.Event.UpdateEventStatus:input_type -> event.UpdateEventStatusReq
	15, // 15: event.Event.CreateShow:input_type -> event.CreateShowReq
	16, // 16: event.Event.UpdateShow:input_type -> event.UpdateShowReq
	22, // 17: event.Event.CreateTicketType:input_type -> event.CreateTicketTypeReq
	23, // 18: event.Event.UpdateTicketType:input_type -> event.UpdateTicketTypeReq
	4,  // 19: event.Event.GetEventList:output_type -> event.GetEventListResp
	6,  // 20: event.Event.GetEvent:output_type -> event.GetEventResp
	12, // 21: event.Event.GetShowList:output_type -> event.GetShowListResp
	14, // 22: event.Event.GetShow:output_type -> event.GetShowResp
	19, // 23: event.Event.GetTicketTypeList:output_type -> event.GetTicketTypeListResp
	21, // 24: event.Event.GetTicketType:output_type -> event.GetTicketTypeResp
	0,  // 25: event.Event.CreateEvent:output_type -> event.CommonResp
	0,  // 26: event.Event.UpdateEvent:output_type -> event.CommonResp
	0,  // 27: event.Event.UpdateEventStatus:output_type -> event.CommonResp
	0,  // 28: event.Event.CreateShow:output_type -> event.CommonResp
	0,  // 29: event.Event.UpdateShow:output_type -> event.CommonResp
	0,  // 30: event.Event.CreateTicketType:output_type -> event.CommonResp
	0,  // 31: event.Event.UpdateTicketType:output_type -> event.CommonResp
	19, // [19:32] is the sub-list for method output_type
	6,  // [6:19] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
