// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.9
// source: event.proto

package event

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Event_GetEventList_FullMethodName      = "/event.Event/GetEventList"
	Event_GetEvent_FullMethodName          = "/event.Event/GetEvent"
	Event_GetShowList_FullMethodName       = "/event.Event/GetShowList"
	Event_GetShow_FullMethodName           = "/event.Event/GetShow"
	Event_GetTicketTypeList_FullMethodName = "/event.Event/GetTicketTypeList"
	Event_GetTicketType_FullMethodName     = "/event.Event/GetTicketType"
	Event_CreateEvent_FullMethodName       = "/event.Event/CreateEvent"
	Event_UpdateEvent_FullMethodName       = "/event.Event/UpdateEvent"
	Event_UpdateEventStatus_FullMethodName = "/event.Event/UpdateEventStatus"
	Event_CreateShow_FullMethodName        = "/event.Event/CreateShow"
	Event_UpdateShow_FullMethodName        = "/event.Event/UpdateShow"
	Event_CreateTicketType_FullMethodName  = "/event.Event/CreateTicketType"
	Event_UpdateTicketType_FullMethodName  = "/event.Event/UpdateTicketType"
)

// EventClient is the client API for Event service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventClient interface {
	// 获取活动列表
	GetEventList(ctx context.Context, in *GetEventListReq, opts ...grpc.CallOption) (*GetEventListResp, error)
	// 获取活动详情
	GetEvent(ctx context.Context, in *GetEventReq, opts ...grpc.CallOption) (*GetEventResp, error)
	// 获取活动下所有场次
	GetShowList(ctx context.Context, in *GetShowListReq, opts ...grpc.CallOption) (*GetShowListResp, error)
	// 获取场次详情
	GetShow(ctx context.Context, in *GetShowReq, opts ...grpc.CallOption) (*GetShowResp, error)
	// 获取场次下所有票种
	GetTicketTypeList(ctx context.Context, in *GetTicketTypeListReq, opts ...grpc.CallOption) (*GetTicketTypeListResp, error)
	// 获取票种详情（Order 创建订单主要调用）
	GetTicketType(ctx context.Context, in *GetTicketTypeReq, opts ...grpc.CallOption) (*GetTicketTypeResp, error)
	// 创建活动
	CreateEvent(ctx context.Context, in *CreateEventReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 修改活动
	UpdateEvent(ctx context.Context, in *UpdateEventReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 修改活动状态（draft、ready、selling、closed）
	UpdateEventStatus(ctx context.Context, in *UpdateEventStatusReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 创建场次
	CreateShow(ctx context.Context, in *CreateShowReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 修改场次
	UpdateShow(ctx context.Context, in *UpdateShowReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 创建票种
	CreateTicketType(ctx context.Context, in *CreateTicketTypeReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 修改票种
	UpdateTicketType(ctx context.Context, in *UpdateTicketTypeReq, opts ...grpc.CallOption) (*CommonResp, error)
}

type eventClient struct {
	cc grpc.ClientConnInterface
}

func NewEventClient(cc grpc.ClientConnInterface) EventClient {
	return &eventClient{cc}
}

func (c *eventClient) GetEventList(ctx context.Context, in *GetEventListReq, opts ...grpc.CallOption) (*GetEventListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventListResp)
	err := c.cc.Invoke(ctx, Event_GetEventList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) GetEvent(ctx context.Context, in *GetEventReq, opts ...grpc.CallOption) (*GetEventResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventResp)
	err := c.cc.Invoke(ctx, Event_GetEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) GetShowList(ctx context.Context, in *GetShowListReq, opts ...grpc.CallOption) (*GetShowListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShowListResp)
	err := c.cc.Invoke(ctx, Event_GetShowList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) GetShow(ctx context.Context, in *GetShowReq, opts ...grpc.CallOption) (*GetShowResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShowResp)
	err := c.cc.Invoke(ctx, Event_GetShow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) GetTicketTypeList(ctx context.Context, in *GetTicketTypeListReq, opts ...grpc.CallOption) (*GetTicketTypeListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTicketTypeListResp)
	err := c.cc.Invoke(ctx, Event_GetTicketTypeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) GetTicketType(ctx context.Context, in *GetTicketTypeReq, opts ...grpc.CallOption) (*GetTicketTypeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTicketTypeResp)
	err := c.cc.Invoke(ctx, Event_GetTicketType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) CreateEvent(ctx context.Context, in *CreateEventReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Event_CreateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) UpdateEvent(ctx context.Context, in *UpdateEventReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Event_UpdateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) UpdateEventStatus(ctx context.Context, in *UpdateEventStatusReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Event_UpdateEventStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) CreateShow(ctx context.Context, in *CreateShowReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Event_CreateShow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) UpdateShow(ctx context.Context, in *UpdateShowReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Event_UpdateShow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) CreateTicketType(ctx context.Context, in *CreateTicketTypeReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Event_CreateTicketType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) UpdateTicketType(ctx context.Context, in *UpdateTicketTypeReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Event_UpdateTicketType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServer is the server API for Event service.
// All implementations must embed UnimplementedEventServer
// for forward compatibility.
type EventServer interface {
	// 获取活动列表
	GetEventList(context.Context, *GetEventListReq) (*GetEventListResp, error)
	// 获取活动详情
	GetEvent(context.Context, *GetEventReq) (*GetEventResp, error)
	// 获取活动下所有场次
	GetShowList(context.Context, *GetShowListReq) (*GetShowListResp, error)
	// 获取场次详情
	GetShow(context.Context, *GetShowReq) (*GetShowResp, error)
	// 获取场次下所有票种
	GetTicketTypeList(context.Context, *GetTicketTypeListReq) (*GetTicketTypeListResp, error)
	// 获取票种详情（Order 创建订单主要调用）
	GetTicketType(context.Context, *GetTicketTypeReq) (*GetTicketTypeResp, error)
	// 创建活动
	CreateEvent(context.Context, *CreateEventReq) (*CommonResp, error)
	// 修改活动
	UpdateEvent(context.Context, *UpdateEventReq) (*CommonResp, error)
	// 修改活动状态（draft、ready、selling、closed）
	UpdateEventStatus(context.Context, *UpdateEventStatusReq) (*CommonResp, error)
	// 创建场次
	CreateShow(context.Context, *CreateShowReq) (*CommonResp, error)
	// 修改场次
	UpdateShow(context.Context, *UpdateShowReq) (*CommonResp, error)
	// 创建票种
	CreateTicketType(context.Context, *CreateTicketTypeReq) (*CommonResp, error)
	// 修改票种
	UpdateTicketType(context.Context, *UpdateTicketTypeReq) (*CommonResp, error)
	mustEmbedUnimplementedEventServer()
}

// UnimplementedEventServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServer struct{}

func (UnimplementedEventServer) GetEventList(context.Context, *GetEventListReq) (*GetEventListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventList not implemented")
}
func (UnimplementedEventServer) GetEvent(context.Context, *GetEventReq) (*GetEventResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvent not implemented")
}
func (UnimplementedEventServer) GetShowList(context.Context, *GetShowListReq) (*GetShowListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShowList not implemented")
}
func (UnimplementedEventServer) GetShow(context.Context, *GetShowReq) (*GetShowResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShow not implemented")
}
func (UnimplementedEventServer) GetTicketTypeList(context.Context, *GetTicketTypeListReq) (*GetTicketTypeListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTicketTypeList not implemented")
}
func (UnimplementedEventServer) GetTicketType(context.Context, *GetTicketTypeReq) (*GetTicketTypeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTicketType not implemented")
}
func (UnimplementedEventServer) CreateEvent(context.Context, *CreateEventReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEvent not implemented")
}
func (UnimplementedEventServer) UpdateEvent(context.Context, *UpdateEventReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEvent not implemented")
}
func (UnimplementedEventServer) UpdateEventStatus(context.Context, *UpdateEventStatusReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEventStatus not implemented")
}
func (UnimplementedEventServer) CreateShow(context.Context, *CreateShowReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShow not implemented")
}
func (UnimplementedEventServer) UpdateShow(context.Context, *UpdateShowReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateShow not implemented")
}
func (UnimplementedEventServer) CreateTicketType(context.Context, *CreateTicketTypeReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTicketType not implemented")
}
func (UnimplementedEventServer) UpdateTicketType(context.Context, *UpdateTicketTypeReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTicketType not implemented")
}
func (UnimplementedEventServer) mustEmbedUnimplementedEventServer() {}
func (UnimplementedEventServer) testEmbeddedByValue()               {}

// UnsafeEventServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServer will
// result in compilation errors.
type UnsafeEventServer interface {
	mustEmbedUnimplementedEventServer()
}

func RegisterEventServer(s grpc.ServiceRegistrar, srv EventServer) {
	// If the following call panics, it indicates UnimplementedEventServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Event_ServiceDesc, srv)
}

func _Event_GetEventList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).GetEventList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Event_GetEventList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).GetEventList(ctx, req.(*GetEventListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Event_GetEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).GetEvent(ctx, req.(*GetEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_GetShowList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShowListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).GetShowList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Event_GetShowList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).GetShowList(ctx, req.(*GetShowListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_GetShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).GetShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Event_GetShow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).GetShow(ctx, req.(*GetShowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_GetTicketTypeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketTypeListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).GetTicketTypeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Event_GetTicketTypeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).GetTicketTypeList(ctx, req.(*GetTicketTypeListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_GetTicketType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketTypeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).GetTicketType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Event_GetTicketType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).GetTicketType(ctx, req.(*GetTicketTypeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Event_CreateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).CreateEvent(ctx, req.(*CreateEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_UpdateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).UpdateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Event_UpdateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).UpdateEvent(ctx, req.(*UpdateEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_UpdateEventStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEventStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).UpdateEventStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Event_UpdateEventStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).UpdateEventStatus(ctx, req.(*UpdateEventStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_CreateShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).CreateShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Event_CreateShow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).CreateShow(ctx, req.(*CreateShowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_UpdateShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).UpdateShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Event_UpdateShow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).UpdateShow(ctx, req.(*UpdateShowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_CreateTicketType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTicketTypeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).CreateTicketType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Event_CreateTicketType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).CreateTicketType(ctx, req.(*CreateTicketTypeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_UpdateTicketType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTicketTypeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).UpdateTicketType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Event_UpdateTicketType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).UpdateTicketType(ctx, req.(*UpdateTicketTypeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Event_ServiceDesc is the grpc.ServiceDesc for Event service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Event_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event.Event",
	HandlerType: (*EventServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEventList",
			Handler:    _Event_GetEventList_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _Event_GetEvent_Handler,
		},
		{
			MethodName: "GetShowList",
			Handler:    _Event_GetShowList_Handler,
		},
		{
			MethodName: "GetShow",
			Handler:    _Event_GetShow_Handler,
		},
		{
			MethodName: "GetTicketTypeList",
			Handler:    _Event_GetTicketTypeList_Handler,
		},
		{
			MethodName: "GetTicketType",
			Handler:    _Event_GetTicketType_Handler,
		},
		{
			MethodName: "CreateEvent",
			Handler:    _Event_CreateEvent_Handler,
		},
		{
			MethodName: "UpdateEvent",
			Handler:    _Event_UpdateEvent_Handler,
		},
		{
			MethodName: "UpdateEventStatus",
			Handler:    _Event_UpdateEventStatus_Handler,
		},
		{
			MethodName: "CreateShow",
			Handler:    _Event_CreateShow_Handler,
		},
		{
			MethodName: "UpdateShow",
			Handler:    _Event_UpdateShow_Handler,
		},
		{
			MethodName: "CreateTicketType",
			Handler:    _Event_CreateTicketType_Handler,
		},
		{
			MethodName: "UpdateTicketType",
			Handler:    _Event_UpdateTicketType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}
