// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type GetEventReq struct {
	EventId int64 `path:"eventId"`
}

type GetEventResp struct {
	EventID    int64
	Title      string
	Desc       string
	Status     string
	CoverImage string
	StartTime  int64
	EndTime    int64
	Location   string
	TotalStock int32
	Shows      []ShowDetail
}

type GetShowReq struct {
	ShowId int64 `path:"showId"`
}

type GetShowResp struct {
	ShowID      int64
	Name        string
	ShowTime    string
	Venue       string
	TicketTypes []TicketTypeDetail
}

type GetTicketTypeReq struct {
	TicketTypeId int64 `path:"ticketTypeId"`
}

type GetTicketTypeResp struct {
	TicketTypeID int64
	ShowID       int64
	Name         string
	Price        float64
	Stock        int32
}

type ShowDetail struct {
	ShowID   int64
	Name     string
	ShowTime string
	Venue    string
}

type TicketTypeDetail struct {
	TicketTypeID int64
	ShowID       int64
	Name         string
	Price        float64
	Stock        int32
}

// ===================== List =====================

type GetEventListReq struct{}

type EventListItem struct {
	EventID     int64
	Title       string
	Description string
	Location    string
	CoverImage  string
	StartTime   int64
	EndTime     int64
	Status      string
	TotalStock  int32
}

type GetEventListResp struct {
	Events []EventListItem
}

type GetShowListReq struct {
	EventId int64 `form:"eventId"`
}

type ShowListItem struct {
	ShowID    int64
	EventID   int64
	Name      string
	ShowTime  string
	EndTime   string
	Status    string
	SoldCount int32
	SortOrder int32
	Venue     string
}

type GetShowListResp struct {
	Shows []ShowListItem
}

type GetTicketTypeListReq struct {
	ShowId int64 `form:"showId"`
}

type TicketTypeListItem struct {
	TicketTypeID int64
	EventID      int64
	ShowID       int64
	Name         string
	Price        float64
	Stock        int32
	MaxPerUser   int32
	SortOrder    int32
}

type GetTicketTypeListResp struct {
	TicketTypes []TicketTypeListItem
}
