// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type GetEventReq struct {
	EventId int64 `path:"eventId"`
}

type GetEventResp struct {
	EventID    int64
	Title      string
	Desc       string
	Status     string
	CoverImage string
	StartTime  int64
	EndTime    int64
	Location   string
	TotalStock int32
	Shows      []ShowDetail
}

type GetShowReq struct {
	ShowId int64 `path:"showId"`
}

type GetShowResp struct {
	ShowID      int64
	Name        string
	ShowTime    string
	Venue       string
	TicketTypes []TicketTypeDetail
}

type GetTicketTypeReq struct {
	TicketTypeId int64 `path:"ticketTypeId"`
}

type GetTicketTypeResp struct {
	TicketTypeID int64
	ShowID       int64
	Name         string
	Price        float64
	Stock        int32
}

type ShowDetail struct {
	ShowID   int64
	Name     string
	ShowTime string
	Venue    string
}

type TicketTypeDetail struct {
	TicketTypeID int64
	ShowID       int64
	Name         string
	Price        float64
	Stock        int32
}
