// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"Ticket/app/event/event-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/event/:eventId",
				Handler: GetEventHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/show/:showId",
				Handler: GetShowHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ticket-type/:ticketTypeId",
				Handler: GetTicketTypeHandler(serverCtx),
			},
		},
	)
}
