// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: order.proto

package orderclient

import (
	"context"

	"Ticket/app/order/order-rpc/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CancelOrderReq   = order.CancelOrderReq
	CancelOrderResp  = order.CancelOrderResp
	CreateOrderReq   = order.CreateOrderReq
	CreateOrderResp  = order.CreateOrderResp
	DeleteOrderReq   = order.DeleteOrderReq
	DeleteOrderResp  = order.DeleteOrderResp
	GetOrderListReq  = order.GetOrderListReq
	GetOrderListResp = order.GetOrderListResp
	GetOrderReq      = order.GetOrderReq
	GetOrderResp     = order.GetOrderResp
	OrderInfo        = order.OrderInfo
	UpdateOrderReq   = order.UpdateOrderReq
	UpdateOrderResp  = order.UpdateOrderResp
	UpdateStatusReq  = order.UpdateStatusReq
	UpdateStatusResp = order.UpdateStatusResp

	Order interface {
		// 创建订单
		CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
		// 修改订单状态
		UpdateOrderStatus(ctx context.Context, in *UpdateStatusReq, opts ...grpc.CallOption) (*UpdateStatusResp, error)
		// 删除订单
		DeleteOrder(ctx context.Context, in *DeleteOrderReq, opts ...grpc.CallOption) (*DeleteOrderResp, error)
		// 修改订单信息
		UpdateOrder(ctx context.Context, in *UpdateOrderReq, opts ...grpc.CallOption) (*UpdateOrderResp, error)
		// 获取订单详情
		GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error)
		// 获取用户订单列表
		GetOrderList(ctx context.Context, in *GetOrderListReq, opts ...grpc.CallOption) (*GetOrderListResp, error)
		// 取消订单
		CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

// 创建订单
func (m *defaultOrder) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

// 修改订单状态
func (m *defaultOrder) UpdateOrderStatus(ctx context.Context, in *UpdateStatusReq, opts ...grpc.CallOption) (*UpdateStatusResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.UpdateOrderStatus(ctx, in, opts...)
}

// 删除订单
func (m *defaultOrder) DeleteOrder(ctx context.Context, in *DeleteOrderReq, opts ...grpc.CallOption) (*DeleteOrderResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.DeleteOrder(ctx, in, opts...)
}

// 修改订单信息
func (m *defaultOrder) UpdateOrder(ctx context.Context, in *UpdateOrderReq, opts ...grpc.CallOption) (*UpdateOrderResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.UpdateOrder(ctx, in, opts...)
}

// 获取订单详情
func (m *defaultOrder) GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}

// 获取用户订单列表
func (m *defaultOrder) GetOrderList(ctx context.Context, in *GetOrderListReq, opts ...grpc.CallOption) (*GetOrderListResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.GetOrderList(ctx, in, opts...)
}

// 取消订单
func (m *defaultOrder) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}
