// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"Ticket/app/ticket/ticket-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/check",
				Handler: CheckTicketHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail/:ticketId",
				Handler: GetTicketHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: ListTicketHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refund",
				Handler: RefundTicketHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/ticket"),
	)
}
