// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.9
// source: ticket.proto

package ticket

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ticket_CreateTicket_FullMethodName     = "/ticket.Ticket/CreateTicket"
	Ticket_GetTicket_FullMethodName        = "/ticket.Ticket/GetTicket"
	Ticket_ListUserTickets_FullMethodName  = "/ticket.Ticket/ListUserTickets"
	Ticket_VerifyTicket_FullMethodName     = "/ticket.Ticket/VerifyTicket"
	Ticket_RefundTicket_FullMethodName     = "/ticket.Ticket/RefundTicket"
	Ticket_TransferTicket_FullMethodName   = "/ticket.Ticket/TransferTicket"
	Ticket_ListEventTickets_FullMethodName = "/ticket.Ticket/ListEventTickets"
)

// TicketClient is the client API for Ticket service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TicketClient interface {
	// 出票（支付成功后调用）
	CreateTicket(ctx context.Context, in *CreateTicketReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 查询票详情
	GetTicket(ctx context.Context, in *GetTicketReq, opts ...grpc.CallOption) (*TicketInfo, error)
	// 我的票（分页）
	ListUserTickets(ctx context.Context, in *ListUserTicketsReq, opts ...grpc.CallOption) (*ListUserTicketsResp, error)
	// 验票（扫码）
	VerifyTicket(ctx context.Context, in *VerifyTicketReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 退票
	RefundTicket(ctx context.Context, in *RefundTicketReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 转赠
	TransferTicket(ctx context.Context, in *TransferTicketReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 管理员查看某活动所有票
	ListEventTickets(ctx context.Context, in *ListEventTicketsReq, opts ...grpc.CallOption) (*ListEventTicketsResp, error)
}

type ticketClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketClient(cc grpc.ClientConnInterface) TicketClient {
	return &ticketClient{cc}
}

func (c *ticketClient) CreateTicket(ctx context.Context, in *CreateTicketReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Ticket_CreateTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) GetTicket(ctx context.Context, in *GetTicketReq, opts ...grpc.CallOption) (*TicketInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TicketInfo)
	err := c.cc.Invoke(ctx, Ticket_GetTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) ListUserTickets(ctx context.Context, in *ListUserTicketsReq, opts ...grpc.CallOption) (*ListUserTicketsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserTicketsResp)
	err := c.cc.Invoke(ctx, Ticket_ListUserTickets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) VerifyTicket(ctx context.Context, in *VerifyTicketReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Ticket_VerifyTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) RefundTicket(ctx context.Context, in *RefundTicketReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Ticket_RefundTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) TransferTicket(ctx context.Context, in *TransferTicketReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Ticket_TransferTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) ListEventTickets(ctx context.Context, in *ListEventTicketsReq, opts ...grpc.CallOption) (*ListEventTicketsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventTicketsResp)
	err := c.cc.Invoke(ctx, Ticket_ListEventTickets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketServer is the server API for Ticket service.
// All implementations must embed UnimplementedTicketServer
// for forward compatibility.
type TicketServer interface {
	// 出票（支付成功后调用）
	CreateTicket(context.Context, *CreateTicketReq) (*CommonResp, error)
	// 查询票详情
	GetTicket(context.Context, *GetTicketReq) (*TicketInfo, error)
	// 我的票（分页）
	ListUserTickets(context.Context, *ListUserTicketsReq) (*ListUserTicketsResp, error)
	// 验票（扫码）
	VerifyTicket(context.Context, *VerifyTicketReq) (*CommonResp, error)
	// 退票
	RefundTicket(context.Context, *RefundTicketReq) (*CommonResp, error)
	// 转赠
	TransferTicket(context.Context, *TransferTicketReq) (*CommonResp, error)
	// 管理员查看某活动所有票
	ListEventTickets(context.Context, *ListEventTicketsReq) (*ListEventTicketsResp, error)
	mustEmbedUnimplementedTicketServer()
}

// UnimplementedTicketServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTicketServer struct{}

func (UnimplementedTicketServer) CreateTicket(context.Context, *CreateTicketReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTicket not implemented")
}
func (UnimplementedTicketServer) GetTicket(context.Context, *GetTicketReq) (*TicketInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTicket not implemented")
}
func (UnimplementedTicketServer) ListUserTickets(context.Context, *ListUserTicketsReq) (*ListUserTicketsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserTickets not implemented")
}
func (UnimplementedTicketServer) VerifyTicket(context.Context, *VerifyTicketReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyTicket not implemented")
}
func (UnimplementedTicketServer) RefundTicket(context.Context, *RefundTicketReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RefundTicket not implemented")
}
func (UnimplementedTicketServer) TransferTicket(context.Context, *TransferTicketReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferTicket not implemented")
}
func (UnimplementedTicketServer) ListEventTickets(context.Context, *ListEventTicketsReq) (*ListEventTicketsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEventTickets not implemented")
}
func (UnimplementedTicketServer) mustEmbedUnimplementedTicketServer() {}
func (UnimplementedTicketServer) testEmbeddedByValue()                {}

// UnsafeTicketServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicketServer will
// result in compilation errors.
type UnsafeTicketServer interface {
	mustEmbedUnimplementedTicketServer()
}

func RegisterTicketServer(s grpc.ServiceRegistrar, srv TicketServer) {
	// If the following call panics, it indicates UnimplementedTicketServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ticket_ServiceDesc, srv)
}

func _Ticket_CreateTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTicketReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).CreateTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ticket_CreateTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).CreateTicket(ctx, req.(*CreateTicketReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_GetTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).GetTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ticket_GetTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).GetTicket(ctx, req.(*GetTicketReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_ListUserTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserTicketsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).ListUserTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ticket_ListUserTickets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).ListUserTickets(ctx, req.(*ListUserTicketsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_VerifyTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTicketReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).VerifyTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ticket_VerifyTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).VerifyTicket(ctx, req.(*VerifyTicketReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_RefundTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundTicketReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).RefundTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ticket_RefundTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).RefundTicket(ctx, req.(*RefundTicketReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_TransferTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferTicketReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).TransferTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ticket_TransferTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).TransferTicket(ctx, req.(*TransferTicketReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_ListEventTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventTicketsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).ListEventTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ticket_ListEventTickets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).ListEventTickets(ctx, req.(*ListEventTicketsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Ticket_ServiceDesc is the grpc.ServiceDesc for Ticket service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ticket_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ticket.Ticket",
	HandlerType: (*TicketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTicket",
			Handler:    _Ticket_CreateTicket_Handler,
		},
		{
			MethodName: "GetTicket",
			Handler:    _Ticket_GetTicket_Handler,
		},
		{
			MethodName: "ListUserTickets",
			Handler:    _Ticket_ListUserTickets_Handler,
		},
		{
			MethodName: "VerifyTicket",
			Handler:    _Ticket_VerifyTicket_Handler,
		},
		{
			MethodName: "RefundTicket",
			Handler:    _Ticket_RefundTicket_Handler,
		},
		{
			MethodName: "TransferTicket",
			Handler:    _Ticket_TransferTicket_Handler,
		},
		{
			MethodName: "ListEventTickets",
			Handler:    _Ticket_ListEventTickets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ticket.proto",
}
