// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: ticket.proto

package ticket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	mi := &file_ticket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommonResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateTicketReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       uint64                 `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ShowId        uint64                 `protobuf:"varint,3,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	TicketTypeId  uint64                 `protobuf:"varint,4,opt,name=ticket_type_id,json=ticketTypeId,proto3" json:"ticket_type_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,5,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,7,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	DiscountCode  string                 `protobuf:"bytes,8,opt,name=discount_code,json=discountCode,proto3" json:"discount_code,omitempty"`
	RealName      string                 `protobuf:"bytes,9,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	IdCard        string                 `protobuf:"bytes,10,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	Phone         string                 `protobuf:"bytes,11,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketReq) Reset() {
	*x = CreateTicketReq{}
	mi := &file_ticket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketReq) ProtoMessage() {}

func (x *CreateTicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketReq.ProtoReflect.Descriptor instead.
func (*CreateTicketReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTicketReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTicketReq) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateTicketReq) GetShowId() uint64 {
	if x != nil {
		return x.ShowId
	}
	return 0
}

func (x *CreateTicketReq) GetTicketTypeId() uint64 {
	if x != nil {
		return x.TicketTypeId
	}
	return 0
}

func (x *CreateTicketReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreateTicketReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateTicketReq) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *CreateTicketReq) GetDiscountCode() string {
	if x != nil {
		return x.DiscountCode
	}
	return ""
}

func (x *CreateTicketReq) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *CreateTicketReq) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *CreateTicketReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type GetTicketReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      uint64                 `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketReq) Reset() {
	*x = GetTicketReq{}
	mi := &file_ticket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketReq) ProtoMessage() {}

func (x *GetTicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketReq.ProtoReflect.Descriptor instead.
func (*GetTicketReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{2}
}

func (x *GetTicketReq) GetTicketId() uint64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

type TicketInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId        uint64                 `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ShowId         uint64                 `protobuf:"varint,4,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	TicketTypeId   uint64                 `protobuf:"varint,5,opt,name=ticket_type_id,json=ticketTypeId,proto3" json:"ticket_type_id,omitempty"`
	OrderNo        string                 `protobuf:"bytes,6,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"` //订单编号
	Quantity       int32                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`             //购买数量
	TotalPrice     float64                `protobuf:"fixed64,8,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Status         string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	QrCode         string                 `protobuf:"bytes,10,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	DiscountCode   string                 `protobuf:"bytes,11,opt,name=discount_code,json=discountCode,proto3" json:"discount_code,omitempty"`
	RealName       string                 `protobuf:"bytes,12,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	IdCard         string                 `protobuf:"bytes,13,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	Phone          string                 `protobuf:"bytes,14,opt,name=phone,proto3" json:"phone,omitempty"`
	TransferredTo  uint64                 `protobuf:"varint,15,opt,name=transferred_to,json=transferredTo,proto3" json:"transferred_to,omitempty"`
	TransferStatus string                 `protobuf:"bytes,16,opt,name=transfer_status,json=transferStatus,proto3" json:"transfer_status,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TicketInfo) Reset() {
	*x = TicketInfo{}
	mi := &file_ticket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketInfo) ProtoMessage() {}

func (x *TicketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketInfo.ProtoReflect.Descriptor instead.
func (*TicketInfo) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{3}
}

func (x *TicketInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TicketInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TicketInfo) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *TicketInfo) GetShowId() uint64 {
	if x != nil {
		return x.ShowId
	}
	return 0
}

func (x *TicketInfo) GetTicketTypeId() uint64 {
	if x != nil {
		return x.TicketTypeId
	}
	return 0
}

func (x *TicketInfo) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *TicketInfo) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TicketInfo) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *TicketInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TicketInfo) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

func (x *TicketInfo) GetDiscountCode() string {
	if x != nil {
		return x.DiscountCode
	}
	return ""
}

func (x *TicketInfo) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *TicketInfo) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *TicketInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *TicketInfo) GetTransferredTo() uint64 {
	if x != nil {
		return x.TransferredTo
	}
	return 0
}

func (x *TicketInfo) GetTransferStatus() string {
	if x != nil {
		return x.TransferStatus
	}
	return ""
}

func (x *TicketInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TicketInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListUserTicketsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserTicketsReq) Reset() {
	*x = ListUserTicketsReq{}
	mi := &file_ticket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserTicketsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserTicketsReq) ProtoMessage() {}

func (x *ListUserTicketsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserTicketsReq.ProtoReflect.Descriptor instead.
func (*ListUserTicketsReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{4}
}

func (x *ListUserTicketsReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListUserTicketsReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListUserTicketsReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserTicketsReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUserTicketsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*TicketInfo          `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserTicketsResp) Reset() {
	*x = ListUserTicketsResp{}
	mi := &file_ticket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserTicketsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserTicketsResp) ProtoMessage() {}

func (x *ListUserTicketsResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserTicketsResp.ProtoReflect.Descriptor instead.
func (*ListUserTicketsResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{5}
}

func (x *ListUserTicketsResp) GetTickets() []*TicketInfo {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *ListUserTicketsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type VerifyTicketReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      uint64                 `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTicketReq) Reset() {
	*x = VerifyTicketReq{}
	mi := &file_ticket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTicketReq) ProtoMessage() {}

func (x *VerifyTicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTicketReq.ProtoReflect.Descriptor instead.
func (*VerifyTicketReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyTicketReq) GetTicketId() uint64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

type RefundTicketReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      uint64                 `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundTicketReq) Reset() {
	*x = RefundTicketReq{}
	mi := &file_ticket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundTicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundTicketReq) ProtoMessage() {}

func (x *RefundTicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundTicketReq.ProtoReflect.Descriptor instead.
func (*RefundTicketReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{7}
}

func (x *RefundTicketReq) GetTicketId() uint64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

type TransferTicketReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      uint64                 `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	ToUserId      uint64                 `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferTicketReq) Reset() {
	*x = TransferTicketReq{}
	mi := &file_ticket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferTicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferTicketReq) ProtoMessage() {}

func (x *TransferTicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferTicketReq.ProtoReflect.Descriptor instead.
func (*TransferTicketReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{8}
}

func (x *TransferTicketReq) GetTicketId() uint64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *TransferTicketReq) GetToUserId() uint64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

type ListEventTicketsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint64                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventTicketsReq) Reset() {
	*x = ListEventTicketsReq{}
	mi := &file_ticket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventTicketsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventTicketsReq) ProtoMessage() {}

func (x *ListEventTicketsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventTicketsReq.ProtoReflect.Descriptor instead.
func (*ListEventTicketsReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{9}
}

func (x *ListEventTicketsReq) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ListEventTicketsReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEventTicketsReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListEventTicketsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*TicketInfo          `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventTicketsResp) Reset() {
	*x = ListEventTicketsResp{}
	mi := &file_ticket_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventTicketsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventTicketsResp) ProtoMessage() {}

func (x *ListEventTicketsResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventTicketsResp.ProtoReflect.Descriptor instead.
func (*ListEventTicketsResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{10}
}

func (x *ListEventTicketsResp) GetTickets() []*TicketInfo {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *ListEventTicketsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_ticket_proto protoreflect.FileDescriptor

const file_ticket_proto_rawDesc = "" +
	"\n" +
	"\fticket.proto\x12\x06ticket\"@\n" +
	"\n" +
	"CommonResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcd\x02\n" +
	"\x0fCreateTicketReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x04R\aeventId\x12\x17\n" +
	"\ashow_id\x18\x03 \x01(\x04R\x06showId\x12$\n" +
	"\x0eticket_type_id\x18\x04 \x01(\x04R\fticketTypeId\x12\x19\n" +
	"\border_no\x18\x05 \x01(\tR\aorderNo\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\x12\x1f\n" +
	"\vtotal_price\x18\a \x01(\x01R\n" +
	"totalPrice\x12#\n" +
	"\rdiscount_code\x18\b \x01(\tR\fdiscountCode\x12\x1b\n" +
	"\treal_name\x18\t \x01(\tR\brealName\x12\x17\n" +
	"\aid_card\x18\n" +
	" \x01(\tR\x06idCard\x12\x14\n" +
	"\x05phone\x18\v \x01(\tR\x05phone\"+\n" +
	"\fGetTicketReq\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x04R\bticketId\"\x97\x04\n" +
	"\n" +
	"TicketInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\x04R\aeventId\x12\x17\n" +
	"\ashow_id\x18\x04 \x01(\x04R\x06showId\x12$\n" +
	"\x0eticket_type_id\x18\x05 \x01(\x04R\fticketTypeId\x12\x19\n" +
	"\border_no\x18\x06 \x01(\tR\aorderNo\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x05R\bquantity\x12\x1f\n" +
	"\vtotal_price\x18\b \x01(\x01R\n" +
	"totalPrice\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x17\n" +
	"\aqr_code\x18\n" +
	" \x01(\tR\x06qrCode\x12#\n" +
	"\rdiscount_code\x18\v \x01(\tR\fdiscountCode\x12\x1b\n" +
	"\treal_name\x18\f \x01(\tR\brealName\x12\x17\n" +
	"\aid_card\x18\r \x01(\tR\x06idCard\x12\x14\n" +
	"\x05phone\x18\x0e \x01(\tR\x05phone\x12%\n" +
	"\x0etransferred_to\x18\x0f \x01(\x04R\rtransferredTo\x12'\n" +
	"\x0ftransfer_status\x18\x10 \x01(\tR\x0etransferStatus\x12\x1d\n" +
	"\n" +
	"created_at\x18\x11 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\tR\tupdatedAt\"v\n" +
	"\x12ListUserTicketsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"Y\n" +
	"\x13ListUserTicketsResp\x12,\n" +
	"\atickets\x18\x01 \x03(\v2\x12.ticket.TicketInfoR\atickets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\".\n" +
	"\x0fVerifyTicketReq\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x04R\bticketId\".\n" +
	"\x0fRefundTicketReq\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x04R\bticketId\"N\n" +
	"\x11TransferTicketReq\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x04R\bticketId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x04R\btoUserId\"a\n" +
	"\x13ListEventTicketsReq\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x04R\aeventId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\"Z\n" +
	"\x14ListEventTicketsResp\x12,\n" +
	"\atickets\x18\x01 \x03(\v2\x12.ticket.TicketInfoR\atickets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xd2\x03\n" +
	"\x06Ticket\x12;\n" +
	"\fCreateTicket\x12\x17.ticket.CreateTicketReq\x1a\x12.ticket.CommonResp\x125\n" +
	"\tGetTicket\x12\x14.ticket.GetTicketReq\x1a\x12.ticket.TicketInfo\x12J\n" +
	"\x0fListUserTickets\x12\x1a.ticket.ListUserTicketsReq\x1a\x1b.ticket.ListUserTicketsResp\x12;\n" +
	"\fVerifyTicket\x12\x17.ticket.VerifyTicketReq\x1a\x12.ticket.CommonResp\x12;\n" +
	"\fRefundTicket\x12\x17.ticket.RefundTicketReq\x1a\x12.ticket.CommonResp\x12?\n" +
	"\x0eTransferTicket\x12\x19.ticket.TransferTicketReq\x1a\x12.ticket.CommonResp\x12M\n" +
	"\x10ListEventTickets\x12\x1b.ticket.ListEventTicketsReq\x1a\x1c.ticket.ListEventTicketsRespB\n" +
	"Z\b./ticketb\x06proto3"

var (
	file_ticket_proto_rawDescOnce sync.Once
	file_ticket_proto_rawDescData []byte
)

func file_ticket_proto_rawDescGZIP() []byte {
	file_ticket_proto_rawDescOnce.Do(func() {
		file_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ticket_proto_rawDesc), len(file_ticket_proto_rawDesc)))
	})
	return file_ticket_proto_rawDescData
}

var file_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_ticket_proto_goTypes = []any{
	(*CommonResp)(nil),           // 0: ticket.CommonResp
	(*CreateTicketReq)(nil),      // 1: ticket.CreateTicketReq
	(*GetTicketReq)(nil),         // 2: ticket.GetTicketReq
	(*TicketInfo)(nil),           // 3: ticket.TicketInfo
	(*ListUserTicketsReq)(nil),   // 4: ticket.ListUserTicketsReq
	(*ListUserTicketsResp)(nil),  // 5: ticket.ListUserTicketsResp
	(*VerifyTicketReq)(nil),      // 6: ticket.VerifyTicketReq
	(*RefundTicketReq)(nil),      // 7: ticket.RefundTicketReq
	(*TransferTicketReq)(nil),    // 8: ticket.TransferTicketReq
	(*ListEventTicketsReq)(nil),  // 9: ticket.ListEventTicketsReq
	(*ListEventTicketsResp)(nil), // 10: ticket.ListEventTicketsResp
}
var file_ticket_proto_depIdxs = []int32{
	3,  // 0: ticket.ListUserTicketsResp.tickets:type_name -> ticket.TicketInfo
	3,  // 1: ticket.ListEventTicketsResp.tickets:type_name -> ticket.TicketInfo
	1,  // 2: ticket.Ticket.CreateTicket:input_type -> ticket.CreateTicketReq
	2,  // 3: ticket.Ticket.GetTicket:input_type -> ticket.GetTicketReq
	4,  // 4: ticket.Ticket.ListUserTickets:input_type -> ticket.ListUserTicketsReq
	6,  // 5: ticket.Ticket.VerifyTicket:input_type -> ticket.VerifyTicketReq
	7,  // 6: ticket.Ticket.RefundTicket:input_type -> ticket.RefundTicketReq
	8,  // 7: ticket.Ticket.TransferTicket:input_type -> ticket.TransferTicketReq
	9,  // 8: ticket.Ticket.ListEventTickets:input_type -> ticket.ListEventTicketsReq
	0,  // 9: ticket.Ticket.CreateTicket:output_type -> ticket.CommonResp
	3,  // 10: ticket.Ticket.GetTicket:output_type -> ticket.TicketInfo
	5,  // 11: ticket.Ticket.ListUserTickets:output_type -> ticket.ListUserTicketsResp
	0,  // 12: ticket.Ticket.VerifyTicket:output_type -> ticket.CommonResp
	0,  // 13: ticket.Ticket.RefundTicket:output_type -> ticket.CommonResp
	0,  // 14: ticket.Ticket.TransferTicket:output_type -> ticket.CommonResp
	10, // 15: ticket.Ticket.ListEventTickets:output_type -> ticket.ListEventTicketsResp
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_ticket_proto_init() }
func file_ticket_proto_init() {
	if File_ticket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ticket_proto_rawDesc), len(file_ticket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ticket_proto_goTypes,
		DependencyIndexes: file_ticket_proto_depIdxs,
		MessageInfos:      file_ticket_proto_msgTypes,
	}.Build()
	File_ticket_proto = out.File
	file_ticket_proto_goTypes = nil
	file_ticket_proto_depIdxs = nil
}
