// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: event.proto

package server

import (
	"context"

	"Ticket/app/event/event-rpc/event"
	"Ticket/app/event/event-rpc/internal/logic"
	"Ticket/app/event/event-rpc/internal/svc"
)

type EventServer struct {
	svcCtx *svc.ServiceContext
	event.UnimplementedEventServer
}

func NewEventServer(svcCtx *svc.ServiceContext) *EventServer {
	return &EventServer{
		svcCtx: svcCtx,
	}
}

// 获取活动列表
func (s *EventServer) GetEventList(ctx context.Context, in *event.GetEventListReq) (*event.GetEventListResp, error) {
	l := logic.NewGetEventListLogic(ctx, s.svcCtx)
	return l.GetEventList(in)
}

// 获取活动详情
func (s *EventServer) GetEvent(ctx context.Context, in *event.GetEventReq) (*event.GetEventResp, error) {
	l := logic.NewGetEventLogic(ctx, s.svcCtx)
	return l.GetEvent(in)
}

// 获取活动下所有场次
func (s *EventServer) GetShowList(ctx context.Context, in *event.GetShowListReq) (*event.GetShowListResp, error) {
	l := logic.NewGetShowListLogic(ctx, s.svcCtx)
	return l.GetShowList(in)
}

// 获取场次详情
func (s *EventServer) GetShow(ctx context.Context, in *event.GetShowReq) (*event.GetShowResp, error) {
	l := logic.NewGetShowLogic(ctx, s.svcCtx)
	return l.GetShow(in)
}

// 获取场次下所有票种
func (s *EventServer) GetTicketTypeList(ctx context.Context, in *event.GetTicketTypeListReq) (*event.GetTicketTypeListResp, error) {
	l := logic.NewGetTicketTypeListLogic(ctx, s.svcCtx)
	return l.GetTicketTypeList(in)
}

// 获取票种详情（Order 创建订单主要调用）
func (s *EventServer) GetTicketType(ctx context.Context, in *event.GetTicketTypeReq) (*event.GetTicketTypeResp, error) {
	l := logic.NewGetTicketTypeLogic(ctx, s.svcCtx)
	return l.GetTicketType(in)
}

// 创建活动
func (s *EventServer) CreateEvent(ctx context.Context, in *event.CreateEventReq) (*event.CommonResp, error) {
	l := logic.NewCreateEventLogic(ctx, s.svcCtx)
	return l.CreateEvent(in)
}

// 修改活动
func (s *EventServer) UpdateEvent(ctx context.Context, in *event.UpdateEventReq) (*event.CommonResp, error) {
	l := logic.NewUpdateEventLogic(ctx, s.svcCtx)
	return l.UpdateEvent(in)
}

// 修改活动状态（draft、ready、selling、closed）
func (s *EventServer) UpdateEventStatus(ctx context.Context, in *event.UpdateEventStatusReq) (*event.CommonResp, error) {
	l := logic.NewUpdateEventStatusLogic(ctx, s.svcCtx)
	return l.UpdateEventStatus(in)
}

// 创建场次
func (s *EventServer) CreateShow(ctx context.Context, in *event.CreateShowReq) (*event.CommonResp, error) {
	l := logic.NewCreateShowLogic(ctx, s.svcCtx)
	return l.CreateShow(in)
}

// 修改场次
func (s *EventServer) UpdateShow(ctx context.Context, in *event.UpdateShowReq) (*event.CommonResp, error) {
	l := logic.NewUpdateShowLogic(ctx, s.svcCtx)
	return l.UpdateShow(in)
}

// 创建票种
func (s *EventServer) CreateTicketType(ctx context.Context, in *event.CreateTicketTypeReq) (*event.CommonResp, error) {
	l := logic.NewCreateTicketTypeLogic(ctx, s.svcCtx)
	return l.CreateTicketType(in)
}

// 修改票种
func (s *EventServer) UpdateTicketType(ctx context.Context, in *event.UpdateTicketTypeReq) (*event.CommonResp, error) {
	l := logic.NewUpdateTicketTypeLogic(ctx, s.svcCtx)
	return l.UpdateTicketType(in)
}
