// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"Ticket/app/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	auth := serverCtx.AuthMiddleware

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{auth.Handle, serverCtx.Admin},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/event",
					Handler: CreateEventHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/event",
					Handler: UpdateEventHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/event/status",
					Handler: UpdateEventStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/show",
					Handler: CreateShowHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/show",
					Handler: UpdateShowHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/ticket-type",
					Handler: CreateTicketTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/ticket-type",
					Handler: UpdateTicketTypeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin"),
	)
}
