// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BuyTicketReq struct {
	EventID      uint64 `json:"eventId"`
	ShowID       uint64 `json:"showId"`
	TicketTypeID uint64 `json:"ticketTypeId"`
	Quantity     int32  `json:"quantity"`
	RequestId    string `json:"requestId"`
}

type BuyTicketResp struct {
	OrderNo    string  `json:"orderNo"`
	Status     string  `json:"status"`
	TotalPrice float64 `json:"totalPrice"`
	Message    string  `json:"message"`
}

type CancelOrderReq struct {
	OrderNo string `json:"orderNo"`
}

type CancelOrderResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type DeleteOrderReq struct {
	OrderNo string `path:"orderNo"`
}

type DeleteOrderResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type GetOrderInfo struct {
	UserID       uint64  `json:"userId"`
	EventID      uint64  `json:"eventId"`
	ShowID       uint64  `json:"showId"`
	TicketTypeID uint64  `json:"ticketTypeId"`
	OrderNo      string  `json:"orderNo"`
	Quantity     int32   `json:"quantity"`
	TotalPrice   float64 `json:"totalPrice"`
	Status       string  `json:"status"`
}

type GetOrderListReq struct {
}

type GetOrderListResp struct {
	Orders []GetOrderInfo `json:"orders"`
}

type GetOrderReq struct {
	OrderNo string `path:"orderNo"`
}

type GetOrderResp struct {
	UserID       uint64  `json:"userId"`
	EventID      uint64  `json:"eventId"`
	ShowID       uint64  `json:"showId"`
	TicketTypeID uint64  `json:"ticketTypeId"`
	OrderNo      string  `json:"orderNo"`
	Quantity     int32   `json:"quantity"`
	TotalPrice   float64 `json:"totalPrice"`
	Status       string  `json:"status"`
}

type PayOrderReq struct {
	OrderNo   string `json:"orderNo"`
	RequestId string `json:"requestId"`
}

type PayOrderResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type UpdateOrderReq struct {
	OrderNo  string `json:"orderNo"`
	Quantity int32  `json:"quantity"`
}

type UpdateOrderResp struct {
	UserID       uint64  `json:"userId"`
	EventID      uint64  `json:"eventId"`
	ShowID       uint64  `json:"showId"`
	TicketTypeID uint64  `json:"ticketTypeId"`
	OrderNo      string  `json:"orderNo"`
	Quantity     int32   `json:"quantity"`
	TotalPrice   float64 `json:"totalPrice"`
	Status       string  `json:"status"`
}
