// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type GetStockReq struct {
	TicketTypeID uint64 `path:"ticketTypeId"`
}

type GetStockResp struct {
	Success      bool   `json:"success"`
	Message      string `json:"message"`
	TicketTypeID uint64 `json:"ticketTypeId"`
	Stock        int32  `json:"stock"`
}

type UpdateStockReq struct {
	TicketTypeID uint64 `json:"ticketTypeId"`
	Stock        int32  `json:"stock"`
}

type UpdateStockResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}
