// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: pay.proto

package server

import (
	"context"

	"Ticket/app/payment/pay-rpc/internal/logic"
	"Ticket/app/payment/pay-rpc/internal/svc"
	"Ticket/app/payment/pay-rpc/payment"
)

type PaymentServer struct {
	svcCtx *svc.ServiceContext
	payment.UnimplementedPaymentServer
}

func NewPaymentServer(svcCtx *svc.ServiceContext) *PaymentServer {
	return &PaymentServer{
		svcCtx: svcCtx,
	}
}

// 模拟支付
func (s *PaymentServer) Pay(ctx context.Context, in *payment.PayReq) (*payment.PayResp, error) {
	l := logic.NewPayLogic(ctx, s.svcCtx)
	return l.Pay(in)
}
